package com.example.admin.loginsignpage;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Created by admin on 13/02/17.
 */

public class StateMap {
    private static final List<String> chooseCountry = Arrays.asList("Choose States");
    private static final List<String> Afghanistan = Arrays.asList("Choose States","Badakhshan","Badghis","Baghlan","Balkh","Bamian","Farah","Faryab","Ghazni","Ghowr","Helmand","Herat","Jowzjan","Kabol","Kandahar","Kapisa","Konar","Kondoz","Laghman","Lowgar","Nangarhar","Nimruz","Oruzgan","Paktia","Paktika","Parvan","Samangan","Sar-e Pol","Takhar","Vardak","Zabol");
    private static final List<String> Albania = Arrays.asList("Choose States","Berat","Bulqize","Delvine","Devoll (Bilisht)","Diber (Peshkopi)","Durres","Elbasan","Fier","Gjirokaster","Gramsh","Has (Krume)","Kavaje","Kolonje (Erseke)","Korce","Kruje","Kucove","Kukes","Kurbin","Lezhe","Librazhd","Lushnje","Malesi e Madhe (Koplik)","Mallakaster (Ballsh)","Mat (Burrel)","Mirdite (Rreshen)","Peqin","Permet","Pogradec","Puke","Sarande","Shkoder","Skrapar (Corovode)","Tepelene","Tirane (Tirana)","Tirane (Tirana)","Tropoje (Bajram Curri)","Vlore");
    private static final List<String> Algeria=Arrays.asList("Choose States","Adrar","Ain Defla","Ain Temouchent","Alger","Annaba","Batna","Bechar","Bejaia","Biskra","Blida","Bordj Bou Arreridj","Bouira","Boumerdes","Chlef","Constantine","Djelfa","El Bayadh","El Oued","El Tarf","Ghardaia","Guelma","Illizi","Jijel","Khenchela","Laghouat","M'Sila","Mascara","Medea","Mila","Mostaganem","Naama","Oran","Ouargla","Oum el Bouaghi","Relizane","Saida","Setif","Sidi Bel Abbes","Skikda","Souk Ahras","Tamanghasset","Tebessa","Tiaret","Tindouf","Tipaza","Tissemsilt","Tizi Ouzou","Tlemcen");
    private static final List<String> AmericanSamoa=Arrays.asList("Choose States","Eastern","Manu'a","Rose Island","Swains Island","Western");
    private static final List<String> Angola=Arrays.asList("Choose States","Andorra la Vella","Bengo","Benguela","Bie","Cabinda","Canillo","Cuando Cubango","Cuanza Norte","Cuanza Sul","Cunene","Encamp","Escaldes-Engordany","Huambo","Huila","La Massana","Luanda","Lunda Norte","Lunda Sul","Malanje","Moxico","Namibe","Ordino","Sant Julia de Loria","Uige","Zaire");
    private static final List<String> Anguilla=Arrays.asList("Choose States","Anguilla");
    private static final List<String> Antartica=Arrays.asList("Choose States","Antartica");
    private static final List<String> AntiguaAndBarbuda=Arrays.asList("Choose States","Barbuda","Redonda","Saint George","Saint John","Saint Mary","Saint Paul","Saint Peter","Saint Philip");
    private static final List<String> Argentina=Arrays.asList("Choose States","Antartica e Islas del Atlantico Sur","Buenos Aires","Buenos Aires Capital Federal","Catamarca","Chaco","Chubut","Cordoba","Corrientes","Entre Rios","Formosa","Jujuy","La Pampa","La Rioja","Mendoza","Misiones","Neuquen","Rio Negro","Salta","San Juan","San Luis","Santa Cruz","Santa Fe","Santiago del Estero","Tierra del Fuego","Tucuman");
    private static final List<String> Armenia=Arrays.asList("Choose States","Aragatsotn","Ararat","Armavir","Geghark'unik'","Kotayk'","Lorri","Shirak","Syunik'","Tavush","Vayots' Dzor","Yerevan");
    private static final List<String> Aruba=Arrays.asList("Choose States","Aruba");
    private static final List<String> AshmoreAndCartierIsland=Arrays.asList("Choose States","Ashmore and Cartier Island");
    private static final List<String> Australia=Arrays.asList("Choose States","Australian Capital Territory","New South Wales","Northern Territory","Queensland","South Australia","Tasmania","Victoria","Western Australia");
    private static final List<String> Austria=Arrays.asList("Choose States","Burgenland","Kaernten","Niederoesterreich","Oberoesterreich","Salzburg","Steiermark","Tirol","Vorarlberg","Wien");
    private static final List<String> Azerbaijan=Arrays.asList("Choose States","Abseron Rayonu","Agcabadi Rayonu","Agdam Rayonu","Agdas Rayonu","Agstafa Rayonu","Agsu Rayonu","Ali Bayramli Sahari","Astara Rayonu","Baki Sahari","Balakan Rayonu","Barda Rayonu","Beylaqan Rayonu","Bilasuvar Rayonu","Cabrayil Rayonu","Calilabad Rayonu","Daskasan Rayonu","Davaci Rayonu","Fuzuli Rayonu","Gadabay Rayonu","Ganca Sahari","Goranboy Rayonu","Goycay Rayonu","Haciqabul Rayonu","Imisli Rayonu","Ismayilli Rayonu","Kalbacar Rayonu","Kurdamir Rayonu","Lacin Rayonu","Lankaran Rayonu","Lankaran Sahari","Lerik Rayonu","Masalli Rayonu","Mingacevir Sahari","Naftalan Sahari","Naxcivan Muxtar Respublikasi","Neftcala Rayonu","Oguz Rayonu","Qabala Rayonu","Qax Rayonu","Qazax Rayonu","Qobustan Rayonu","Quba Rayonu","Qubadli Rayonu","Qusar Rayonu","Saatli Rayonu","Sabirabad Rayonu","Saki Rayonu","Saki Sahari","Salyan Rayonu","Samaxi Rayonu","Samkir Rayonu","Samux Rayonu","Siyazan Rayonu","Sumqayit Sahari","Susa Rayonu","Susa Sahari","Tartar Rayonu","Tovuz Rayonu","Ucar Rayonu","Xacmaz Rayonu","Xankandi Sahari","Xanlar Rayonu","Xizi Rayonu","Xocali Rayonu","Xocavand Rayonu","Yardimli Rayonu","Yevlax Rayonu","Yevlax Sahari","Zangilan Rayonu","Zaqatala Rayonu","Zardab Rayonu");
    private static final List<String> Bahamas=Arrays.asList("Choose States","Acklins and Crooked Islands","Bimini","Cat Island","Exuma","Freeport","Fresh Creek","Governor's Harbour","Green Turtle Cay","Harbour Island","High Rock","Inagua","Kemps Bay","Long Island","Marsh Harbour","Mayaguana","New Providence","Nicholls Town and Berry Islands","Ragged Island","Rock Sound","San Salvador and Rum Cay","Sandy Point");
    private static final List<String> Bahrain=Arrays.asList("Choose States","Al Hadd","Al Manamah","Al Mintaqah al Gharbiyah","Al Mintaqah al Wusta","Al Mintaqah ash Shamaliyah","Al Muharraq","Ar Rifa' wa al Mintaqah al Janubiyah","Jidd Hafs","Juzur Hawar","Madinat 'Isa","Madinat Hamad","Sitrah");
    private static final List<String> Bangladesh=Arrays.asList("Choose States","Barguna","Barisal","Bhola","Jhalokati","Patuakhali","Pirojpur","Bandarban","Brahmanbaria","Chandpur","Chittagong","Comilla","Cox's Bazar","Feni","Khagrachari","Lakshmipur","Noakhali","Rangamati","Dhaka","Faridpur","Gazipur","Gopalganj","Jamalpur","Kishoreganj","Madaripur","Manikganj","Munshiganj","Mymensingh","Narayanganj","Narsingdi","Netrokona","Rajbari","Shariatpur","Sherpur","Tangail","Bagerhat","Chuadanga","Jessore","Jhenaidah","Khulna","Kushtia","Magura","Meherpur","Narail","Satkhira","Bogra","Dinajpur","Gaibandha","Jaipurhat","Kurigram","Lalmonirhat","Naogaon","Natore","Nawabganj","Nilphamari","Pabna","Panchagarh","Rajshahi","Rangpur","Sirajganj","Thakurgaon","Habiganj","Maulvi bazar","Sunamganj","Sylhet");
    private static final List<String> Barbados=Arrays.asList("Choose States","Bridgetown","Christ Church","Saint Andrew","Saint George","Saint James","Saint John","Saint Joseph","Saint Lucy","Saint Michael","Saint Peter","Saint Philip","Saint Thomas");
    private static final List<String> Belarus=Arrays.asList("Choose States","Brestskaya (Brest)","Homyel'skaya (Homyel')","Horad Minsk","Hrodzyenskaya (Hrodna)","Mahilyowskaya (Mahilyow)","Minskaya","Vitsyebskaya (Vitsyebsk)");
    private static final List<String> Belgium=Arrays.asList("Choose States","Antwerpen","Brabant Wallon","Brussels Capitol Region","Hainaut","Liege","Limburg","Luxembourg","Namur","Oost-Vlaanderen","Vlaams Brabant","West-Vlaanderen");
    private static final List<String> Belize=Arrays.asList("Choose States","Belize","Cayo","Corozal","Orange Walk","Stann Creek","Toledo");
    private static final List<String> Benin=Arrays.asList("Choose States","Alibori","Atakora","Atlantique","Borgou","Collines","Couffo","Donga","Littoral","Mono","Oueme","Plateau","Zou");
    private static final List<String> Bermuda=Arrays.asList("Choose States","Devonshire","Hamilton","Hamilton","Paget","Pembroke","Saint George","Saint Georges","Sandys","Smiths","Southampton","Warwick");
    private static final List<String> Bhutan=Arrays.asList("Choose States","Bumthang","Chhukha","Chirang","Daga","Geylegphug","Ha","Lhuntshi","Mongar","Paro","Pemagatsel","Punakha","Samchi","Samdrup Jongkhar","Shemgang","Tashigang","Thimphu","Tongsa","Wangdi Phodrang");
    private static final List<String> Bolivia=Arrays.asList("Choose States","Beni","Chuquisaca","Cochabamba","La Paz","Oruro","Pando","Potosi","Santa Cruz","Tarija");
    private static final List<String> BosniaAndHerzegovina=Arrays.asList("Choose States","Federation of Bosnia and Herzegovina","Republika Srpska");
    private static final List<String> Botswana=Arrays.asList("Choose States","Central","Chobe","Francistown","Gaborone","Ghanzi","Kgalagadi","Kgatleng","Kweneng","Lobatse","Ngamiland","North-East","Selebi-Pikwe","South-East","Southern");
    private static final List<String> Brazil=Arrays.asList("Choose States","Acre","Alagoas","Amapa","Amazonas","Bahia","Ceara","Distrito Federal","Espirito Santo","Goias","Maranhao","Mato Grosso","Mato Grosso do Sul","Minas Gerais","Para","Paraiba","Parana","Pernambuco","Piaui","Rio de Janeiro","Rio Grande do Norte","Rio Grande do Sul","Rondonia","Roraima","Santa Catarina","Sao Paulo","Sergipe","Tocantins");
    private static final List<String> BritishVirginIslands=Arrays.asList("Choose States","Anegada","Jost Van Dyke","Tortola","Virgin Gorda");
    private static final List<String> Brunei=Arrays.asList("Choose States","Belait","Brunei and Muara","Temburong","Tutong");
    private static final List<String> Bulgaria=Arrays.asList("Choose States","Blagoevgrad","Burgas","Dobrich","Gabrovo","Khaskovo","Kurdzhali","Kyustendil","Lovech","Montana","Pazardzhik","Pernik","Pleven","Plovdiv","Razgrad","Ruse","Shumen","Silistra","Sliven","Smolyan","Sofiya","Sofiya-Grad","Stara Zagora","Turgovishte","Varna","Veliko Turnovo","Vidin","Vratsa","Yambol");
    private static final List<String> BurkinaFaso=Arrays.asList("Choose States","Bale","Bam","Banwa","Bazega","Bougouriba","Boulgou","Boulkiemde","Comoe","Ganzourgou","Gnagna","Gourma","Houet","Ioba","Kadiogo","Kenedougou","Komandjari","Kompienga","Kossi","Koupelogo","Kouritenga","Kourweogo","Leraba","Loroum","Mouhoun","Nahouri","Namentenga","Naumbiel","Nayala","Oubritenga","Oudalan","Passore","Poni","Samentenga","Sanguie","Seno","Sissili","Soum","Sourou","Tapoa","Tuy","Yagha","Yatenga","Ziro","Zondomo","Zoundweogo");
    private static final List<String> Burma=Arrays.asList("Choose States","Ayeyarwady","Bago","Chin State","Kachin State","Kayah State","Kayin State","Magway","Mandalay","Mon State","Rakhine State","Sagaing","Shan State","Tanintharyi","Yangon");
    private static final List<String> Burundi=Arrays.asList("Choose States","Bubanza","Bujumbura","Bururi","Cankuzo","Cibitoke","Gitega","Karuzi","Kayanza","Kirundo","Makamba","Muramvya","Muyinga","Mwaro","Ngozi","Rutana","Ruyigi");
    private static final List<String> Cambodia=Arrays.asList("Choose States","Banteay Mean Cheay","Batdambang","Kampong Cham","Kampong Chhnang","Kampong Spoe","Kampong Thum","Kampot","Kandal","Kaoh Kong","Keb","Kracheh","Mondol Kiri","Otdar Mean Cheay","Pailin","Phnum Penh","Pouthisat","Preah Seihanu (Sihanoukville)","Preah Vihear","Prey Veng","Rotanah Kiri","Siem Reab","Stoeng Treng","Svay Rieng","Takev");
    private static final List<String> Cameroon=Arrays.asList("Choose States","Adamaoua","Centre","Est","Extreme-Nord","Littoral","Nord","Nord-Ouest","Ouest","Sud","Sud-Ouest");
    private static final List<String> Canada=Arrays.asList("Choose States","Alberta","British Columbia","Manitoba","New Brunswick","Newfoundland","Northwest Territories","Nova Scotia","Nunavut","Ontario","Prince Edward Island","Quebec","Saskatchewan","Yukon Territory");
    private static final List<String> CapeVerde=Arrays.asList("Choose States","Boa Vista","Brava","Maio","Mosteiros","Paul","Porto Novo","Praia","Ribeira Grande","Sal","Santa Catarina","Santa Cruz","Sao Domingos","Sao Filipe","Sao Nicolau","Sao Vicente","Tarrafal");
    private static final List<String> CaymanIslands=Arrays.asList("Choose States","Creek","Eastern","Midland","South Town","Spot Bay","Stake Bay","West End","Western");
    private static final List<String> CentralAfricanRepublic=Arrays.asList("Choose States","Bamingui-Bangoran","Bangui","Basse-Kotto","Gribingui","Haut-Mbomou","Haute-Kotto","Haute-Sangha","Kemo-Gribingui","Lobaye","Mbomou","Nana-Mambere","Ombella-Mpoko","Ouaka","Ouham","Ouham-Pende","Sangha","Vakaga");
    private static final List<String> Chad=Arrays.asList("Choose States","Batha","Biltine","Borkou-Ennedi-Tibesti","Chari-Baguirmi","Guera","Kanem","Lac","Logone Occidental","Logone Oriental","Mayo-Kebbi","Moyen-Chari","Ouaddai","Salamat","Tandjile");
    private static final List<String> Chile=Arrays.asList("Choose States","Aisen del General Carlos Ibanez del Campo","Antofagasta","Araucania","Atacama","Bio-Bio","Coquimbo","Libertador General Bernardo O'Higgins","Los Lagos","Magallanes y de la Antartica Chilena","Maule","Region Metropolitana (Santiago)","Tarapaca","Valparaiso");
    private static final List<String> China=Arrays.asList("Choose States","Anhui","Beijing","Chongqing","Fujian","Gansu","Guangdong","Guangxi","Guizhou","Hainan","Hebei","Heilongjiang","Henan","Hubei","Hunan","Jiangsu","Jiangxi","Jilin","Liaoning","Nei Mongol","Ningxia","Qinghai","Shaanxi","Shandong","Shanghai","Shanxi","Sichuan","Tianjin","Xinjiang","Xizang (Tibet)","Yunnan","Zhejiang");
    private static final List<String> ChristmasIsland=Arrays.asList("Choose States","Christmas Island");
    private static final List<String> ClippertonIsland=Arrays.asList("Choose States","Clipperton Island");
    private static final List<String> CocosIslands=Arrays.asList("Choose States","Direction Island","Home Island","Horsburgh Island","North Keeling Island","South Island","West Island");
    private static final List<String> Colombia=Arrays.asList("Choose States","Amazonas","Antioquia","Arauca","Atlantico","Bolivar","Boyaca","Caldas","Caqueta","Casanare","Cauca","Cesar","Choco","Cordoba","Cundinamarca","Distrito Capital de Santa Fe de Bogota","Guainia","Guaviare","Huila","La Guajira","Magdalena","Meta","Narino","Norte de Santander","Putumayo","Quindio","Risaralda","San Andres y Providencia","Santander","Sucre","Tolima","Valle del Cauca","Vaupes","Vichada");
    private static final List<String> Comoros=Arrays.asList("Choose States","Anjouan (Nzwani)","Domoni","Fomboni","Grande Comore (Njazidja)","Moheli (Mwali)","Moroni","Moutsamoudou");
    private static final List<String> CongoDemocraticRepublicOfThe=Arrays.asList("Choose States","Bandundu","Bas-Congo","Equateur","Kasai-Occidental","Kasai-Oriental","Katanga","Kinshasa","Maniema","Nord-Kivu","Orientale","Sud-Kivu");
    private static final List<String> CongoRepublicOfThe=Arrays.asList("Choose States","Bouenza","Brazzaville","Cuvette","Kouilou","Lekoumou","Likouala","Niari","Plateaux","Pool","Sangha");
    private static final List<String> CookIslands=Arrays.asList("Choose States","Aitutaki","Atiu","Avarua","Mangaia","Manihiki","Manuae","Mauke","Mitiaro","Nassau Island","Palmerston","Penrhyn","Pukapuka","Rakahanga","Rarotonga","Suwarrow","Takutea");
    private static final List<String> CostaRica=Arrays.asList("Choose States","Alajuela","Cartago","Guanacaste","Heredia","Limon","Puntarenas","San Jose");
    private static final List<String> CoteDIvoire=Arrays.asList("Choose States","Abengourou","Abidjan","Aboisso","Adiake'","Adzope","Agboville","Agnibilekrou","Ale'pe'","Bangolo","Beoumi","Biankouma","Bocanda","Bondoukou","Bongouanou","Bouafle","Bouake","Bouna","Boundiali","Dabakala","Dabon","Daloa","Danane","Daoukro","Dimbokro","Divo","Duekoue","Ferkessedougou","Gagnoa","Grand Bassam","Grand-Lahou","Guiglo","Issia","Jacqueville","Katiola","Korhogo","Lakota","Man","Mankono","Mbahiakro","Odienne","Oume","Sakassou","San-Pedro","Sassandra","Seguela","Sinfra","Soubre","Tabou","Tanda","Tiassale","Tiebissou","Tingrela","Touba","Toulepleu","Toumodi","Vavoua","Yamoussoukro","Zuenoula");
    private static final List<String> Croatia=Arrays.asList("Choose States","Bjelovarsko-Bilogorska Zupanija","Brodsko-Posavska Zupanija","Dubrovacko-Neretvanska Zupanija","Istarska Zupanija","Karlovacka Zupanija","Koprivnicko-Krizevacka Zupanija","Krapinsko-Zagorska Zupanija","Licko-Senjska Zupanija","Medimurska Zupanija","Osjecko-Baranjska Zupanija","Pozesko-Slavonska Zupanija","Primorsko-Goranska Zupanija","Sibensko-Kninska Zupanija","Sisacko-Moslavacka Zupanija","Splitsko-Dalmatinska Zupanija","Varazdinska Zupanija","Viroviticko-Podravska Zupanija","Vukovarsko-Srijemska Zupanija","Zadarska Zupanija","Zagreb","Zagrebacka Zupanija");
    private static final List<String> Cuba=Arrays.asList("Choose States","Camaguey","Ciego de Avila","Cienfuegos","Ciudad de La Habana","Granma","Guantanamo","Holguin","Isla de la Juventud","La Habana","Las Tunas","Matanzas","Pinar del Rio","Sancti Spiritus","Santiago de Cuba","Villa Clara");
    private static final List<String> Cyprus=Arrays.asList("Choose States","Famagusta","Kyrenia","Larnaca","Limassol","Nicosia","Paphos");
    private static final List<String> CzeckRepublic=Arrays.asList("Choose States","Brnensky","Budejovicky","Jihlavsky","Karlovarsky","Kralovehradecky","Liberecky","Olomoucky","Ostravsky","Pardubicky","Plzensky","Praha","Stredocesky","Ustecky","Zlinsky");
    private static final List<String> Denmark=Arrays.asList("Choose States","Arhus","Bornholm","Fredericksberg","Frederiksborg","Fyn","Kobenhavn","Kobenhavns","Nordjylland","Ribe","Ringkobing","Roskilde","Sonderjylland","Storstrom","Vejle","Vestsjalland","Viborg");
    private static final List<String> Djibouti=Arrays.asList("Choose States","Ali Sabih","Dikhil","Djibouti","Obock","Tadjoura");
    private static final List<String> Dominica=Arrays.asList("Choose States","Saint Andrew","Saint David","Saint George","Saint John","Saint Joseph","Saint Luke","Saint Mark","Saint Patrick","Saint Paul","Saint Peter");
    private static final List<String> DominicanRepublic=Arrays.asList("Choose States","Azua","Baoruco","Barahona","Dajabon","Distrito Nacional","Duarte","El Seibo","Elias Pina","Espaillat","Hato Mayor","Independencia","La Altagracia","La Romana","La Vega","Maria Trinidad Sanchez","Monsenor Nouel","Monte Cristi","Monte Plata","Pedernales","Peravia","Puerto Plata","Salcedo","Samana","San Cristobal","San Juan","San Pedro de Macoris","Sanchez Ramirez","Santiago","Santiago Rodriguez","Valverde");
    private static final List<String> Ecuador=Arrays.asList("Choose States","Azuay","Bolivar","Canar","Carchi","Chimborazo","Cotopaxi","El Oro","Esmeraldas","Galapagos","Guayas","Imbabura","Loja","Los Rios","Manabi","Morona-Santiago","Napo","Orellana","Pastaza","Pichincha","Sucumbios","Tungurahua","Zamora-Chinchipe");
    private static final List<String> Egypt=Arrays.asList("Choose States","Ad Daqahliyah","Al Bahr al Ahmar","Al Buhayrah","Al Fayyum","Al Gharbiyah","Al Iskandariyah","Al Isma'iliyah","Al Jizah","Al Minufiyah","Al Minya","Al Qahirah","Al Qalyubiyah","Al Wadi al Jadid","As Suways","Ash Sharqiyah","Aswan","Asyut","Bani Suwayf","Bur Sa'id","Dumyat","Janub Sina'","Kafr ash Shaykh","Matruh","Qina","Shamal Sina'","Suhaj");
    private static final List<String> ElSalvador=Arrays.asList("Choose States","Ahuachapan","Cabanas","Chalatenango","Cuscatlan","La Libertad","La Paz","La Union","Morazan","San Miguel","San Salvador","San Vicente","Santa Ana","Sonsonate","Usulutan");
    private static final List<String> EquatorialGuinea=Arrays.asList("Choose States","Annobon","Bioko Norte","Bioko Sur","Centro Sur","Kie-Ntem","Litoral","Wele-Nzas");
    private static final List<String> Eritrea=Arrays.asList("Choose States","Akale Guzay","Barka","Denkel","Hamasen","Sahil","Semhar","Senhit","Seraye");
    private static final List<String> Estonia=Arrays.asList("Choose States","Harjumaa (Tallinn)","Hiiumaa (Kardla)","Ida-Virumaa (Johvi)","Jarvamaa (Paide)","Jogevamaa (Jogeva)","Laane-Virumaa (Rakvere)","Laanemaa (Haapsalu)","Parnumaa (Parnu)","Polvamaa (Polva)","Raplamaa (Rapla)","Saaremaa (Kuessaare)","Tartumaa (Tartu)","Valgamaa (Valga)","Viljandimaa (Viljandi)","Vorumaa (Voru)");
    private static final List<String> Ethiopia=Arrays.asList("Choose States","Adis Abeba (Addis Ababa)","Afar","Amara","Dire Dawa","Gambela Hizboch","Hareri Hizb","Oromiya","Sumale","Tigray","YeDebub Biheroch Bihereseboch na Hizboch");
    private static final List<String> EuropaIsland=Arrays.asList("Choose States","Europa Island");
    private static final List<String> FalklandIslands=Arrays.asList("Choose States","Falkland Islands (Islas Malvinas)");
    private static final List<String> FaroeIslands=Arrays.asList("Choose States","Bordoy","Eysturoy","Mykines","Sandoy","Skuvoy","Streymoy","Suduroy","Tvoroyri","Vagar");
    private static final List<String> Fiji=Arrays.asList("Choose States","Central","Eastern","Northern","Rotuma","Western");
    private static final List<String> Finland=Arrays.asList("Choose States","Aland","Etela-Suomen Laani","Ita-Suomen Laani","Lansi-Suomen Laani","Lappi","Oulun Laani");
    private static final List<String> France=Arrays.asList("Choose States","Alsace","Aquitaine","Auvergne","Basse-Normandie","Bourgogne","Bretagne","Centre","Champagne-Ardenne","Corse","Franche-Comte","Haute-Normandie","Ile-de-France","Languedoc-Roussillon","Limousin","Lorraine","Midi-Pyrenees","Nord-Pas-de-Calais","Pays de la Loire","Picardie","Poitou-Charentes","Provence-Alpes-Cote d'Azur","Rhone-Alpes");
    private static final List<String> FrenchGuiana=Arrays.asList("Choose States","French Guiana");
    private static final List<String> FrenchPolynesia=Arrays.asList("Choose States","Archipel des Marquises","Archipel des Tuamotu","Archipel des Tubuai","Iles du Vent","Iles Sous-le-Vent");
    private static final List<String> FrenchSouthernAndAntarcticLands=Arrays.asList("Choose States","Adelie Land","Ile Crozet","Iles Kerguelen","Iles Saint-Paul et Amsterdam");
    private static final List<String> Gabon=Arrays.asList("Choose States","Estuaire","Haut-Ogooue","Moyen-Ogooue","Ngounie","Nyanga","Ogooue-Ivindo","Ogooue-Lolo","Ogooue-Maritime","Woleu-Ntem");
    private static final List<String> GambiaThe=Arrays.asList("Choose States","Banjul","Central River","Lower River","North Bank","Upper River","Western");
    private static final List<String> GazaStrip=Arrays.asList("Choose States","Gaza Strip");
    private static final List<String> Georgia=Arrays.asList("Choose States","Abashis","Abkhazia or Ap'khazet'is Avtonomiuri Respublika (Sokhumi)","Adigenis","Ajaria or Acharis Avtonomiuri Respublika (Bat'umi)","Akhalgoris","Akhalk'alak'is","Akhalts'ikhis","Akhmetis","Ambrolauris","Aspindzis","Baghdat'is","Bolnisis","Borjomis","Ch'khorotsqus","Ch'okhatauris","Chiat'ura","Dedop'listsqaros","Dmanisis","Dushet'is","Gardabanis","Gori","Goris","Gurjaanis","Javis","K'arelis","K'ut'aisi","Kaspis","Kharagaulis","Khashuris","Khobis","Khonis","Lagodekhis","Lanch'khut'is","Lentekhis","Marneulis","Martvilis","Mestiis","Mts'khet'is","Ninotsmindis","Onis","Ozurget'is","P'ot'i","Qazbegis","Qvarlis","Rust'avi","Sach'kheris","Sagarejos","Samtrediis","Senakis","Sighnaghis","T'bilisi","T'elavis","T'erjolis","T'et'ritsqaros","T'ianet'is","Tqibuli","Ts'ageris","Tsalenjikhis","Tsalkis","Tsqaltubo","Vanis","Zestap'onis","Zugdidi","Zugdidis");
    private static final List<String> Germany=Arrays.asList("Choose States","Baden-Wuerttemberg","Bayern","Berlin","Brandenburg","Bremen","Hamburg","Hessen","Mecklenburg-Vorpommern","Niedersachsen","Nordrhein-Westfalen","Rheinland-Pfalz","Saarland","Sachsen","Sachsen-Anhalt","Schleswig-Holstein","Thueringen");
    private static final List<String> Ghana=Arrays.asList("Choose States","Ashanti","Brong-Ahafo","Central","Eastern","Greater Accra","Northern","Upper East","Upper West","Volta","Western");
    private static final List<String> Gibraltar=Arrays.asList("Choose States","Gibraltar");
    private static final List<String> GloriosoIslands=Arrays.asList("Choose States","Ile du Lys","Ile Glorieuse");
    private static final List<String> Greece=Arrays.asList("Choose States","Aitolia kai Akarnania","Akhaia","Argolis","Arkadhia","Arta","Attiki","Ayion Oros (Mt. Athos)","Dhodhekanisos","Drama","Evritania","Evros","Evvoia","Florina","Fokis","Fthiotis","Grevena","Ilia","Imathia","Ioannina","Irakleion","Kardhitsa","Kastoria","Kavala","Kefallinia","Kerkyra","Khalkidhiki","Khania","Khios","Kikladhes","Kilkis","Korinthia","Kozani","Lakonia","Larisa","Lasithi","Lesvos","Levkas","Magnisia","Messinia","Pella","Pieria","Preveza","Rethimni","Rodhopi","Samos","Serrai","Thesprotia","Thessaloniki","Trikala","Voiotia","Xanthi","Zakinthos");
    private static final List<String> Greenland=Arrays.asList("Choose States","Avannaa (Nordgronland)","Kitaa (Vestgronland)","Tunu (Ostgronland)");
    private static final List<String> Grenada=Arrays.asList("Choose States","Carriacou and Petit Martinique","Saint Andrew","Saint David","Saint George","Saint John","Saint Mark","Saint Patrick");
    private static final List<String> Guadeloupe=Arrays.asList("Choose States","Basse-Terre","Grande-Terre","Iles de la Petite Terre","Iles des Saintes","Marie-Galante");
    private static final List<String> Guam=Arrays.asList("Choose States","Guam");
    private static final List<String> Guatemala=Arrays.asList("Choose States","Alta Verapaz","Baja Verapaz","Chimaltenango","Chiquimula","El Progreso","Escuintla","Guatemala","Huehuetenango","Izabal","Jalapa","Jutiapa","Peten","Quetzaltenango","Quiche","Retalhuleu","Sacatepequez","San Marcos","Santa Rosa","Solola","Suchitepequez","Totonicapan","Zacapa");
    private static final List<String> Guernsey=Arrays.asList("Choose States","Castel","Forest","St. Andrew","St. Martin","St. Peter Port","St. Pierre du Bois","St. Sampson","St. Saviour","Torteval","Vale");
    private static final List<String> Guinea=Arrays.asList("Choose States","Beyla","Boffa","Boke","Conakry","Coyah","Dabola","Dalaba","Dinguiraye","Dubreka","Faranah","Forecariah","Fria","Gaoual","Gueckedou","Kankan","Kerouane","Kindia","Kissidougou","Koubia","Koundara","Kouroussa","Labe","Lelouma","Lola","Macenta","Mali","Mamou","Mandiana","Nzerekore","Pita","Siguiri","Telimele","Tougue","Yomou");
    private static final List<String> GuineaBissau=Arrays.asList("Choose States","Bafata","Biombo","Bissau","Bolama-Bijagos","Cacheu","Gabu","Oio","Quinara","Tombali");
    private static final List<String> Guyana=Arrays.asList("Choose States","Barima-Waini","Cuyuni-Mazaruni","Demerara-Mahaica","East Berbice-Corentyne","Essequibo Islands-West Demerara","Mahaica-Berbice","Pomeroon-Supenaam","Potaro-Siparuni","Upper Demerara-Berbice","Upper Takutu-Upper Essequibo");
    private static final List<String> Haiti=Arrays.asList("Choose States","Artibonite","Centre","Grand'Anse","Nord","Nord-Est","Nord-Ouest","Ouest","Sud","Sud-Est");
    private static final List<String> HeardIslandAndMcDonaldIslands=Arrays.asList("Choose States","Heard Island and McDonald Islands");
    private static final List<String> HolySee=Arrays.asList("Choose States","Holy See (Vatican City)");
    private static final List<String> Honduras=Arrays.asList("Choose States","Atlantida","Choluteca","Colon","Comayagua","Copan","Cortes","El Paraiso","Francisco Morazan","Gracias a Dios","Intibuca","Islas de la Bahia","La Paz","Lempira","Ocotepeque","Olancho","Santa Barbara","Valle","Yoro");
    private static final List<String> HongKong=Arrays.asList("Choose States","Hong Kong");
    private static final List<String> HowlandIsland=Arrays.asList("Choose States","Howland Island");
    private static final List<String> Hungary=Arrays.asList("Choose States","Bacs-Kiskun","Baranya","Bekes","Bekescsaba","Borsod-Abauj-Zemplen","Budapest","Csongrad","Debrecen","Dunaujvaros","Eger","Fejer","Gyor","Gyor-Moson-Sopron","Hajdu-Bihar","Heves","Hodmezovasarhely","Jasz-Nagykun-Szolnok","Kaposvar","Kecskemet","Komarom-Esztergom","Miskolc","Nagykanizsa","Nograd","Nyiregyhaza","Pecs","Pest","Somogy","Sopron","Szabolcs-Szatmar-Bereg","Szeged","Szekesfehervar","Szolnok","Szombathely","Tatabanya","Tolna","Vas","Veszprem","Veszprem","Zala","Zalaegerszeg");
    private static final List<String> Iceland=Arrays.asList("Choose States","Akranes","Akureyri","Arnessysla","Austur-Bardhastrandarsysla","Austur-Hunavatnssysla","Austur-Skaftafellssysla","Borgarfjardharsysla","Dalasysla","Eyjafjardharsysla","Gullbringusysla","Hafnarfjordhur","Husavik","Isafjordhur","Keflavik","Kjosarsysla","Kopavogur","Myrasysla","Neskaupstadhur","Nordhur-Isafjardharsysla","Nordhur-Mulasys-la","Nordhur-Thingeyjarsysla","Olafsfjordhur","Rangarvallasysla","Reykjavik","Saudharkrokur","Seydhisfjordhur","Siglufjordhur","Skagafjardharsysla","Snaefellsnes-og Hnappadalssysla","Strandasysla","Sudhur-Mulasysla","Sudhur-Thingeyjarsysla","Vesttmannaeyjar","Vestur-Bardhastrandarsysla","Vestur-Hunavatnssysla","Vestur-Isafjardharsysla","Vestur-Skaftafellssysla");
    private static final List<String> India=Arrays.asList("Choose States","Andaman and Nicobar Islands","Andhra Pradesh","Arunachal Pradesh","Assam","Bihar","Chandigarh","Chhattisgarh","Dadra and Nagar Haveli","Daman and Diu","Delhi","Goa","Gujarat","Haryana","Himachal Pradesh","Jammu and Kashmir","Jharkhand","Karnataka","Kerala","Lakshadweep","Madhya Pradesh","Maharashtra","Manipur","Meghalaya","Mizoram","Nagaland","Orissa","Pondicherry","Punjab","Rajasthan","Sikkim","Tamil Nadu","Tripura","Uttar Pradesh","Uttaranchal","West Bengal");
    private static final List<String> Indonesia=Arrays.asList("Choose States","Aceh","Bali","Banten","Bengkulu","East Timor","Gorontalo","Irian Jaya","Jakarta Raya","Jambi","Jawa Barat","Jawa Tengah","Jawa Timur","Kalimantan Barat","Kalimantan Selatan","Kalimantan Tengah","Kalimantan Timur","Kepulauan Bangka Belitung","Lampung","Maluku","Maluku Utara","Nusa Tenggara Barat","Nusa Tenggara Timur","Riau","Sulawesi Selatan","Sulawesi Tengah","Sulawesi Tenggara","Sulawesi Utara","Sumatera Barat","Sumatera Selatan","Sumatera Utara","Yogyakarta");
    private static final List<String> Iran=Arrays.asList("Choose States","Ardabil","Azarbayjan-e Gharbi","Azarbayjan-e Sharqi","Bushehr","Chahar Mahall va Bakhtiari","Esfahan","Fars","Gilan","Golestan","Hamadan","Hormozgan","Ilam","Kerman","Kermanshah","Khorasan","Khuzestan","Kohgiluyeh va Buyer Ahmad","Kordestan","Lorestan","Markazi","Mazandaran","Qazvin","Qom","Semnan","Sistan va Baluchestan","Tehran","Yazd","Zanjan");
    private static final List<String> Iraq=Arrays.asList("Choose States","Al Anbar","Al Basrah","Al Muthanna","Al Qadisiyah","An Najaf","Arbil","As Sulaymaniyah","At Ta'mim","Babil","Baghdad","Dahuk","Dhi Qar","Diyala","Karbala'","Maysan","Ninawa","Salah ad Din","Wasit");
    private static final List<String> Ireland=Arrays.asList("Choose States","Carlow","Cavan","Clare","Cork","Donegal","Dublin","Galway","Kerry","Kildare","Kilkenny","Laois","Leitrim","Limerick","Longford","Louth","Mayo","Meath","Monaghan","Offaly","Roscommon","Sligo","Tipperary","Waterford","Westmeath","Wexford","Wicklow");
    private static final List<String> IrelandNorthern=Arrays.asList("Choose States","Antrim","Ards","Armagh","Ballymena","Ballymoney","Banbridge","Belfast","Carrickfergus","Castlereagh","Coleraine","Cookstown","Craigavon","Derry","Down","Dungannon","Fermanagh","Larne","Limavady","Lisburn","Magherafelt","Moyle","Newry and Mourne","Newtownabbey","North Down","Omagh","Strabane");
    private static final List<String> Israel=Arrays.asList("Choose States","Central","Haifa","Jerusalem","Northern","Southern","Tel Aviv");
    private static final List<String> Italy=Arrays.asList("Choose States","Abruzzo","Basilicata","Calabria","Campania","Emilia-Romagna","Friuli-Venezia Giulia","Lazio","Liguria","Lombardia","Marche","Molise","Piemonte","Puglia","Sardegna","Sicilia","Toscana","Trentino-Alto Adige","Umbria","Valle d'Aosta","Veneto");
    private static final List<String> Jamaica=Arrays.asList("Choose States","Clarendon","Hanover","Kingston","Manchester","Portland","Saint Andrew","Saint Ann","Saint Catherine","Saint Elizabeth","Saint James","Saint Mary","Saint Thomas","Trelawny","Westmoreland");
    private static final List<String> JanMayen=Arrays.asList("Choose States","Jan Mayen");
    private static final List<String> Japan=Arrays.asList("Choose States","Aichi","Akita","Aomori","Chiba","Ehime","Fukui","Fukuoka","Fukushima","Gifu","Gumma","Hiroshima","Hokkaido","Hyogo","Ibaraki","Ishikawa","Iwate","Kagawa","Kagoshima","Kanagawa","Kochi","Kumamoto","Kyoto","Mie","Miyagi","Miyazaki","Nagano","Nagasaki","Nara","Niigata","Oita","Okayama","Okinawa","Osaka","Saga","Saitama","Shiga","Shimane","Shizuoka","Tochigi","Tokushima","Tokyo","Tottori","Toyama","Wakayama","Yamagata","Yamaguchi","Yamanashi");
    private static final List<String> JarvisIsland=Arrays.asList("Choose States","Jarvis Island");
    private static final List<String> Jersey=Arrays.asList("Choose States","Jersey");
    private static final List<String> JohnstonAtoll=Arrays.asList("Choose States","Johnston Atoll");
    private static final List<String> Jordan=Arrays.asList("Choose States","'Amman","Ajlun","Al 'Aqabah","Al Balqa'","Al Karak","Al Mafraq","At Tafilah","Az Zarqa'","Irbid","Jarash","Ma'an","Madaba");
    private static final List<String> JuanDeNovaIsland=Arrays.asList("Choose States","Juan de Nova Island");
    private static final List<String> Kazakhstan=Arrays.asList("Choose States","Almaty","Aqmola","Aqtobe","Astana","Atyrau","Batys Qazaqstan","Bayqongyr","Mangghystau","Ongtustik Qazaqstan","Pavlodar","Qaraghandy","Qostanay","Qyzylorda","Shyghys Qazaqstan","Soltustik Qazaqstan","Zhambyl");
    private static final List<String> Kenya=Arrays.asList("Choose States","Central","Coast","Eastern","Nairobi Area","North Eastern","Nyanza","Rift Valley","Western");
    private static final List<String> Kiribati=Arrays.asList("Choose States","Abaiang","Abemama","Aranuka","Arorae","Banaba","Banaba","Beru","Butaritari","Central Gilberts","Gilbert Islands","Kanton","Kiritimati","Kuria","Line Islands","Line Islands","Maiana","Makin","Marakei","Nikunau","Nonouti","Northern Gilberts","Onotoa","Phoenix Islands","Southern Gilberts","Tabiteuea","Tabuaeran","Tamana","Tarawa","Tarawa","Teraina");
    private static final List<String> KoreaNorth=Arrays.asList("Choose States","Chagang-do (Chagang Province)","Hamgyong-bukto (North Hamgyong Province)","Hamgyong-namdo (South Hamgyong Province)","Hwanghae-bukto (North Hwanghae Province)","Hwanghae-namdo (South Hwanghae Province)","Kaesong-si (Kaesong City)","Kangwon-do (Kangwon Province)","Namp'o-si (Namp'o City)","P'yongan-bukto (North P'yongan Province)","P'yongan-namdo (South P'yongan Province)","P'yongyang-si (P'yongyang City)","Yanggang-do (Yanggang Province)");
    private static final List<String> KoreaSouth=Arrays.asList("Choose States","Ch'ungch'ong-bukto","Ch'ungch'ong-namdo","Cheju-do","Cholla-bukto","Cholla-namdo","Inch'on-gwangyoksi","Kangwon-do","Kwangju-gwangyoksi","Kyonggi-do","Kyongsang-bukto","Kyongsang-namdo","Pusan-gwangyoksi","Soul-t'ukpyolsi","Taegu-gwangyoksi","Taejon-gwangyoksi","Ulsan-gwangyoksi");
    private static final List<String> Kuwait=Arrays.asList("Choose States","Al 'Asimah","Al Ahmadi","Al Farwaniyah","Al Jahra'","Hawalli");
    private static final List<String> Kyrgyzstan=Arrays.asList("Choose States","Batken Oblasty","Bishkek Shaary","Chuy Oblasty (Bishkek)","Jalal-Abad Oblasty","Naryn Oblasty","Osh Oblasty","Talas Oblasty","Ysyk-Kol Oblasty (Karakol)");
    private static final List<String> Laos=Arrays.asList("Choose States","Attapu","Bokeo","Bolikhamxai","Champasak","Houaphan","Khammouan","Louangnamtha","Louangphabang","Oudomxai","Phongsali","Salavan","Savannakhet","Viangchan","Viangchan","Xaignabouli","Xaisomboun","Xekong","Xiangkhoang");
    private static final List<String> Latvia=Arrays.asList("Choose States","Aizkraukles Rajons","Aluksnes Rajons","Balvu Rajons","Bauskas Rajons","Cesu Rajons","Daugavpils","Daugavpils Rajons","Dobeles Rajons","Gulbenes Rajons","Jekabpils Rajons","Jelgava","Jelgavas Rajons","Jurmala","Kraslavas Rajons","Kuldigas Rajons","Leipaja","Liepajas Rajons","Limbazu Rajons","Ludzas Rajons","Madonas Rajons","Ogres Rajons","Preilu Rajons","Rezekne","Rezeknes Rajons","Riga","Rigas Rajons","Saldus Rajons","Talsu Rajons","Tukuma Rajons","Valkas Rajons","Valmieras Rajons","Ventspils","Ventspils Rajons");
    private static final List<String> Lebanon=Arrays.asList("Choose States","Beyrouth","Ech Chimal","Ej Jnoub","El Bekaa","Jabal Loubnane");
    private static final List<String> Lesotho=Arrays.asList("Choose States","Berea","Butha-Buthe","Leribe","Mafeteng","Maseru","Mohales Hoek","Mokhotlong","Qacha's Nek","Quthing","Thaba-Tseka");
    private static final List<String> Liberia=Arrays.asList("Choose States","Bomi","Bong","Grand Bassa","Grand Cape Mount","Grand Gedeh","Grand Kru","Lofa","Margibi","Maryland","Montserrado","Nimba","River Cess","Sinoe");
    private static final List<String> Libya=Arrays.asList("Choose States","Ajdabiya","Al 'Aziziyah","Al Fatih","Al Jabal al Akhdar","Al Jufrah","Al Khums","Al Kufrah","An Nuqat al Khams","Ash Shati'","Awbari","Az Zawiyah","Banghazi","Darnah","Ghadamis","Gharyan","Misratah","Murzuq","Sabha","Sawfajjin","Surt","Tarabulus","Tarhunah","Tubruq","Yafran","Zlitan");
    private static final List<String> Liechtenstein=Arrays.asList("Choose States","Balzers","Eschen","Gamprin","Mauren","Planken","Ruggell","Schaan","Schellenberg","Triesen","Triesenberg","Vaduz");
    private static final List<String> Lithuania=Arrays.asList("Choose States","Akmenes Rajonas","Alytaus Rajonas","Alytus","Anyksciu Rajonas","Birstonas","Birzu Rajonas","Druskininkai","Ignalinos Rajonas","Jonavos Rajonas","Joniskio Rajonas","Jurbarko Rajonas","Kaisiadoriu Rajonas","Kaunas","Kauno Rajonas","Kedainiu Rajonas","Kelmes Rajonas","Klaipeda","Klaipedos Rajonas","Kretingos Rajonas","Kupiskio Rajonas","Lazdiju Rajonas","Marijampole","Marijampoles Rajonas","Mazeikiu Rajonas","Moletu Rajonas","Neringa Pakruojo Rajonas","Palanga","Panevezio Rajonas","Panevezys","Pasvalio Rajonas","Plunges Rajonas","Prienu Rajonas","Radviliskio Rajonas","Raseiniu Rajonas","Rokiskio Rajonas","Sakiu Rajonas","Salcininku Rajonas","Siauliai","Siauliu Rajonas","Silales Rajonas","Silutes Rajonas","Sirvintu Rajonas","Skuodo Rajonas","Svencioniu Rajonas","Taurages Rajonas","Telsiu Rajonas","Traku Rajonas","Ukmerges Rajonas","Utenos Rajonas","Varenos Rajonas","Vilkaviskio Rajonas","Vilniaus Rajonas","Vilnius","Zarasu Rajonas");
    private static final List<String> Luxembourg=Arrays.asList("Choose States","Diekirch","Grevenmacher","Luxembourg");
    private static final List<String> Macau=Arrays.asList("Choose States","Macau");
    private static final List<String> MacedoniaFormerYugoslavRepublicOf=Arrays.asList("Choose States","Aracinovo","Bac","Belcista","Berovo","Bistrica","Bitola","Blatec","Bogdanci","Bogomila","Bogovinje","Bosilovo","Brvenica","Cair (Skopje)","Capari","Caska","Cegrane","Centar (Skopje)","Centar Zupa","Cesinovo","Cucer-Sandevo","Debar","Delcevo","Delogozdi","Demir Hisar","Demir Kapija","Dobrusevo","Dolna Banjica","Dolneni","Dorce Petrov (Skopje)","Drugovo","Dzepciste","Gazi Baba (Skopje)","Gevgelija","Gostivar","Gradsko","Ilinden","Izvor","Jegunovce","Kamenjane","Karbinci","Karpos (Skopje)","Kavadarci","Kicevo","Kisela Voda (Skopje)","Klecevce","Kocani","Konce","Kondovo","Konopiste","Kosel","Kratovo","Kriva Palanka","Krivogastani","Krusevo","Kuklis","Kukurecani","Kumanovo","Labunista","Lipkovo","Lozovo","Lukovo","Makedonska Kamenica","Makedonski Brod","Mavrovi Anovi","Meseista","Miravci","Mogila","Murtino","Negotino","Negotino-Poloska","Novaci","Novo Selo","Oblesevo","Ohrid","Orasac","Orizari","Oslomej","Pehcevo","Petrovec","Plasnia","Podares","Prilep","Probistip","Radovis","Rankovce","Resen","Rosoman","Rostusa","Samokov","Saraj","Sipkovica","Sopiste","Sopotnika","Srbinovo","Star Dojran","Staravina","Staro Nagoricane","Stip","Struga","Strumica","Studenicani","Suto Orizari (Skopje)","Sveti Nikole","Tearce","Tetovo","Topolcani","Valandovo","Vasilevo","Veles","Velesta","Vevcani","Vinica","Vitoliste","Vranestica","Vrapciste","Vratnica","Vrutok","Zajas","Zelenikovo","Zileno","Zitose","Zletovo","Zrnovci");
    private static final List<String> Madagascar=Arrays.asList("Choose States","Antananarivo","Antsiranana","Fianarantsoa","Mahajanga","Toamasina","Toliara");
    private static final List<String> Malawi=Arrays.asList("Choose States","Balaka","Blantyre","Chikwawa","Chiradzulu","Chitipa","Dedza","Dowa","Karonga","Kasungu","Likoma","Lilongwe","Machinga (Kasupe)","Mangochi","Mchinji","Mulanje","Mwanza","Mzimba","Nkhata Bay","Nkhotakota","Nsanje","Ntcheu","Ntchisi","Phalombe","Rumphi","Salima","Thyolo","Zomba");
    private static final List<String> Malaysia=Arrays.asList("Choose States","Johor","Kedah","Kelantan","Labuan","Melaka","Negeri Sembilan","Pahang","Perak","Perlis","Pulau Pinang","Sabah","Sarawak","Selangor","Terengganu","Wilayah Persekutuan");
    private static final List<String> Maldives=Arrays.asList("Choose States","Alifu","Baa","Dhaalu","Faafu","Gaafu Alifu","Gaafu Dhaalu","Gnaviyani","Haa Alifu","Haa Dhaalu","Kaafu","Laamu","Lhaviyani","Maale","Meemu","Noonu","Raa","Seenu","Shaviyani","Thaa","Vaavu");
    private static final List<String> Mali=Arrays.asList("Choose States","Gao","Kayes","Kidal","Koulikoro","Mopti","Segou","Sikasso","Tombouctou");
    private static final List<String> Malta=Arrays.asList("Choose States","Valletta");
    private static final List<String> ManIsleOf=Arrays.asList("Choose States","Man, Isle of");
    private static final List<String> MarshallIslands=Arrays.asList("Choose States","Ailinginae","Ailinglaplap","Ailuk","Arno","Aur","Bikar","Bikini","Bokak","Ebon","Enewetak","Erikub","Jabat","Jaluit","Jemo","Kili","Kwajalein","Lae","Lib","Likiep","Majuro","Maloelap","Mejit","Mili","Namorik","Namu","Rongelap","Rongrik","Toke","Ujae","Ujelang","Utirik","Wotho","Wotje");
    private static final List<String> Martinique=Arrays.asList("Choose States","Martinique");
    private static final List<String> Mauritania=Arrays.asList("Choose States","Adrar","Assaba","Brakna","Dakhlet Nouadhibou","Gorgol","Guidimaka","Hodh Ech Chargui","Hodh El Gharbi","Inchiri","Nouakchott","Tagant","Tiris Zemmour","Trarza");
    private static final List<String> Mauritius=Arrays.asList("Choose States","Agalega Islands","Black River","Cargados Carajos Shoals","Flacq","Grand Port","Moka","Pamplemousses","Plaines Wilhems","Port Louis","Riviere du Rempart","Rodrigues","Savanne");
    private static final List<String> Mayotte=Arrays.asList("Choose States","Mayotte");
    private static final List<String> Mexico=Arrays.asList("Choose States","Aguascalientes","Baja California","Baja California Sur","Campeche","Chiapas","Chihuahua","Coahuila de Zaragoza","Colima","Distrito Federal","Durango","Guanajuato","Guerrero","Hidalgo","Jalisco","Mexico","Michoacan de Ocampo","Morelos","Nayarit","Nuevo Leon","Oaxaca","Puebla","Queretaro de Arteaga","Quintana Roo","San Luis Potosi","Sinaloa","Sonora","Tabasco","Tamaulipas","Tlaxcala","Veracruz-Llave","Yucatan","Zacatecas");
    private static final List<String> MicronesiaFederatedStatesOf=Arrays.asList("Choose States","Chuuk (Truk)","Kosrae","Pohnpei","Yap");
    private static final List<String> MidwayIslands=Arrays.asList("Choose States","Midway Islands");
    private static final List<String> Moldova=Arrays.asList("Choose States","Balti","Cahul","Chisinau","Chisinau","Dubasari","Edinet","Gagauzia","Lapusna","Orhei","Soroca","Tighina","Ungheni");
    private static final List<String> Monaco=Arrays.asList("Choose States","Fontvieille","La Condamine","Monaco-Ville","Monte-Carlo");
    private static final List<String> Mongolia=Arrays.asList("Choose States","Arhangay","Bayan-Olgiy","Bayanhongor","Bulgan","Darhan","Dornod","Dornogovi","Dundgovi","Dzavhan","Erdenet","Govi-Altay","Hentiy","Hovd","Hovsgol","Omnogovi","Ovorhangay","Selenge","Suhbaatar","Tov","Ulaanbaatar","Uvs");
    private static final List<String> Montserrat=Arrays.asList("Choose States","Saint Anthony","Saint Georges","Saint Peter's");
    private static final List<String> Morocco=Arrays.asList("Choose States","Agadir","Al Hoceima","Azilal","Ben Slimane","Beni Mellal","Boulemane","Casablanca","Chaouen","El Jadida","El Kelaa des Srarhna","Er Rachidia","Essaouira","Fes","Figuig","Guelmim","Ifrane","Kenitra","Khemisset","Khenifra","Khouribga","Laayoune","Larache","Marrakech","Meknes","Nador","Ouarzazate","Oujda","Rabat-Sale","Safi","Settat","Sidi Kacem","Tan-Tan","Tanger","Taounate","Taroudannt","Tata","Taza","Tetouan","Tiznit");
    private static final List<String> Mozambique=Arrays.asList("Choose States","Cabo Delgado","Gaza","Inhambane","Manica","Maputo","Nampula","Niassa","Sofala","Tete","Zambezia");
    private static final List<String> Namibia=Arrays.asList("Choose States","Caprivi","Erongo","Hardap","Karas","Khomas","Kunene","Ohangwena","Okavango","Omaheke","Omusati","Oshana","Oshikoto","Otjozondjupa");
    private static final List<String> Nauru=Arrays.asList("Choose States","Aiwo","Anabar","Anetan","Anibare","Baiti","Boe","Buada","Denigomodu","Ewa","Ijuw","Meneng","Nibok","Uaboe","Yaren");
    private static final List<String> Nepal=Arrays.asList("Choose States","Bagmati","Bheri","Dhawalagiri","Gandaki","Janakpur","Karnali","Kosi","Lumbini","Mahakali","Mechi","Narayani","Rapti","Sagarmatha","Seti");
    private static final List<String> Netherlands=Arrays.asList("Choose States","Drenthe","Flevoland","Friesland","Gelderland","Groningen","Limburg","Noord-Brabant","Noord-Holland","Overijssel","Utrecht","Zeeland","Zuid-Holland");
    private static final List<String> NetherlandsAntilles=Arrays.asList("Choose States","Netherlands Antilles");
    private static final List<String> NewCaledonia=Arrays.asList("Choose States","Iles Loyaute","Nord","Sud");
    private static final List<String> NewZealand=Arrays.asList("Choose States","Akaroa","Amuri","Ashburton","Bay of Islands","Bruce","Buller","Chatham Islands","Cheviot","Clifton","Clutha","Cook","Dannevirke","Egmont","Eketahuna","Ellesmere","Eltham","Eyre","Featherston","Franklin","Golden Bay","Great Barrier Island","Grey","Hauraki Plains","Hawera","Hawke's Bay","Heathcote","Hikurangi","Hobson","Hokianga","Horowhenua","Hurunui","Hutt","Inangahua","Inglewood","Kaikoura","Kairanga","Kiwitea","Lake","Mackenzie","Malvern","Manaia","Manawatu","Mangonui","Maniototo","Marlborough","Masterton","Matamata","Mount Herbert","Ohinemuri","Opotiki","Oroua","Otamatea","Otorohanga","Oxford","Pahiatua","Paparua","Patea","Piako","Pohangina","Raglan","Rangiora","Rangitikei","Rodney","Rotorua","Runanga","Saint Kilda","Silverpeaks","Southland","Stewart Island","Stratford","Strathallan","Taranaki","Taumarunui","Taupo","Tauranga","Thames-Coromandel","Tuapeka","Vincent","Waiapu","Waiheke","Waihemo","Waikato","Waikohu","Waimairi","Waimarino","Waimate","Waimate West","Waimea","Waipa","Waipawa","Waipukurau","Wairarapa South","Wairewa","Wairoa","Waitaki","Waitomo","Waitotara","Wallace","Wanganui","Waverley","Westland","Whakatane","Whangarei","Whangaroa","Woodville");
    private static final List<String> Nicaragua=Arrays.asList("Choose States","Atlantico Norte","Atlantico Sur","Boaco","Carazo","Chinandega","Chontales","Esteli","Granada","Jinotega","Leon","Madriz","Managua","Masaya","Matagalpa","Nueva Segovia","Rio San Juan","Rivas");
    private static final List<String> Niger=Arrays.asList("Choose States","Agadez","Diffa","Dosso","Maradi","Niamey","Tahoua","Tillaberi","Zinder");
    private static final List<String> Nigeria=Arrays.asList("Choose States","Abia","Abuja Federal Capital Territory","Adamawa","Akwa Ibom","Anambra","Bauchi","Bayelsa","Benue","Borno","Cross River","Delta","Ebonyi","Edo","Ekiti","Enugu","Gombe","Imo","Jigawa","Kaduna","Kano","Katsina","Kebbi","Kogi","Kwara","Lagos","Nassarawa","Niger","Ogun","Ondo","Osun","Oyo","Plateau","Rivers","Sokoto","Taraba","Yobe","Zamfara");
    private static final List<String> Niue=Arrays.asList("Choose States","Niue");
    private static final List<String> NorfolkIsland=Arrays.asList("Choose States","Norfolk Island");
    private static final List<String> NorthernMarianaIslands=Arrays.asList("Choose States","Northern Islands","Rota","Saipan","Tinian");
    private static final List<String> Norway=Arrays.asList("Choose States","Akershus","Aust-Agder","Buskerud","Finnmark","Hedmark","Hordaland","More og Romsdal","Nord-Trondelag","Nordland","Oppland","Oslo","Ostfold","Rogaland","Sogn og Fjordane","Sor-Trondelag","Telemark","Troms","Vest-Agder","Vestfold");
    private static final List<String> Oman=Arrays.asList("Choose States","Ad Dakhiliyah","Al Batinah","Al Wusta","Ash Sharqiyah","Az Zahirah","Masqat","Musandam","Zufar");
    private static final List<String> Pakistan=Arrays.asList("Choose States","Balochistan","Federally Administered Tribal Areas","Islamabad Capital Territory","North-West Frontier Province","Punjab","Sindh");
    private static final List<String> Palau=Arrays.asList("Choose States","Aimeliik","Airai","Angaur","Hatobohei","Kayangel","Koror","Melekeok","Ngaraard","Ngarchelong","Ngardmau","Ngatpang","Ngchesar","Ngeremlengui","Ngiwal","Palau Island","Peleliu","Sonsoral","Tobi");
    private static final List<String> Panama=Arrays.asList("Choose States","Bocas del Toro","Chiriqui","Cocle","Colon","Darien","Herrera","Los Santos","Panama","San Blas","Veraguas");
    private static final List<String> PapuaNewGuinea=Arrays.asList("Choose States","Bougainville","Central","Chimbu","East New Britain","East Sepik","Eastern Highlands","Enga","Gulf","Madang","Manus","Milne Bay","Morobe","National Capital","New Ireland","Northern","Sandaun","Southern Highlands","West New Britain","Western","Western Highlands");
    private static final List<String> Paraguay=Arrays.asList("Choose States","Alto Paraguay","Alto Parana","Amambay","Asuncion (city)","Boqueron","Caaguazu","Caazapa","Canindeyu","Central","Concepcion","Cordillera","Guaira","Itapua","Misiones","Neembucu","Paraguari","Presidente Hayes","San Pedro");
    private static final List<String> Peru=Arrays.asList("Choose States","Amazonas","Ancash","Apurimac","Arequipa","Ayacucho","Cajamarca","Callao","Cusco","Huancavelica","Huanuco","Ica","Junin","La Libertad","Lambayeque","Lima","Loreto","Madre de Dios","Moquegua","Pasco","Piura","Puno","San Martin","Tacna","Tumbes","Ucayali");
    private static final List<String> Philippines=Arrays.asList("Choose States","Abra","Agusan del Norte","Agusan del Sur","Aklan","Albay","Angeles","Antique","Aurora","Bacolod","Bago","Baguio","Bais","Basilan","Basilan City","Bataan","Batanes","Batangas","Batangas City","Benguet","Bohol","Bukidnon","Bulacan","Butuan","Cabanatuan","Cadiz","Cagayan","Cagayan de Oro","Calbayog","Caloocan","Camarines Norte","Camarines Sur","Camiguin","Canlaon","Capiz","Catanduanes","Cavite","Cavite City","Cebu","Cebu City","Cotabato","Dagupan","Danao","Dapitan","Davao City Davao","Davao del Sur","Davao Oriental","Dipolog","Dumaguete","Eastern Samar","General Santos","Gingoog","Ifugao","Iligan","Ilocos Norte","Ilocos Sur","Iloilo","Iloilo City","Iriga","Isabela","Kalinga-Apayao","La Carlota","La Union","Laguna","Lanao del Norte","Lanao del Sur","Laoag","Lapu-Lapu","Legaspi","Leyte","Lipa","Lucena","Maguindanao","Mandaue","Manila","Marawi","Marinduque","Masbate","Mindoro Occidental","Mindoro Oriental","Misamis Occidental","Misamis Oriental","Mountain","Naga","Negros Occidental","Negros Oriental","North Cotabato","Northern Samar","Nueva Ecija","Nueva Vizcaya","Olongapo","Ormoc","Oroquieta","Ozamis","Pagadian","Palawan","Palayan","Pampanga","Pangasinan","Pasay","Puerto Princesa","Quezon","Quezon City","Quirino","Rizal","Romblon","Roxas","Samar","San Carlos (in Negros Occidental)","San Carlos (in Pangasinan)","San Jose","San Pablo","Silay","Siquijor","Sorsogon","South Cotabato","Southern Leyte","Sultan Kudarat","Sulu","Surigao","Surigao del Norte","Surigao del Sur","Tacloban","Tagaytay","Tagbilaran","Tangub","Tarlac","Tawitawi","Toledo","Trece Martires","Zambales","Zamboanga","Zamboanga del Norte","Zamboanga del Sur");
    private static final List<String> PitcaimIslands=Arrays.asList("Choose States","Pitcaim Islands");
    private static final List<String> Poland=Arrays.asList("Choose States","Dolnoslaskie","Kujawsko-Pomorskie","Lodzkie","Lubelskie","Lubuskie","Malopolskie","Mazowieckie","Opolskie","Podkarpackie","Podlaskie","Pomorskie","Slaskie","Swietokrzyskie","Warminsko-Mazurskie","Wielkopolskie","Zachodniopomorskie");
    private static final List<String> Portugal=Arrays.asList("Choose States","Acores (Azores)","Aveiro","Beja","Braga","Braganca","Castelo Branco","Coimbra","Evora","Faro","Guarda","Leiria","Lisboa","Madeira","Portalegre","Porto","Santarem","Setubal","Viana do Castelo","Vila Real","Viseu");
    private static final List<String> PuertoRico=Arrays.asList("Choose States","Adjuntas","Aguada","Aguadilla","Aguas Buenas","Aibonito","Anasco","Arecibo","Arroyo","Barceloneta","Barranquitas","Bayamon","Cabo Rojo","Caguas","Camuy","Canovanas","Carolina","Catano","Cayey","Ceiba","Ciales","Cidra","Coamo","Comerio","Corozal","Culebra","Dorado","Fajardo","Florida","Guanica","Guayama","Guayanilla","Guaynabo","Gurabo","Hatillo","Hormigueros","Humacao","Isabela","Jayuya","Juana Diaz","Juncos","Lajas","Lares","Las Marias","Las Piedras","Loiza","Luquillo","Manati","Maricao","Maunabo","Mayaguez","Moca","Morovis","Naguabo","Naranjito","Orocovis","Patillas","Penuelas","Ponce","Quebradillas","Rincon","Rio Grande","Sabana Grande","Salinas","San German","San Juan","San Lorenzo","San Sebastian","Santa Isabel","Toa Alta","Toa Baja","Trujillo Alto","Utuado","Vega Alta","Vega Baja","Vieques","Villalba","Yabucoa","Yauco");
    private static final List<String> Qatar=Arrays.asList("Choose States","Ad Dawhah","Al Ghuwayriyah","Al Jumayliyah","Al Khawr","Al Wakrah","Ar Rayyan","Jarayan al Batinah","Madinat ash Shamal","Umm Salal");
    private static final List<String> Reunion=Arrays.asList("Choose States","Reunion");
    private static final List<String> Romainia=Arrays.asList("Choose States","Alba","Arad","Arges","Bacau","Bihor","Bistrita-Nasaud","Botosani","Braila","Brasov","Bucuresti","Buzau","Calarasi","Caras-Severin","Cluj","Constanta","Covasna","Dimbovita","Dolj","Galati","Giurgiu","Gorj","Harghita","Hunedoara","Ialomita","Iasi","Maramures","Mehedinti","Mures","Neamt","Olt","Prahova","Salaj","Satu Mare","Sibiu","Suceava","Teleorman","Timis","Tulcea","Vaslui","Vilcea","Vrancea");
    private static final List<String> Russia=Arrays.asList("Choose States","Adygeya (Maykop)","Aginskiy Buryatskiy (Aginskoye)","Altay (Gorno-Altaysk)","Altayskiy (Barnaul)","Amurskaya (Blagoveshchensk)","Arkhangel'skaya","Astrakhanskaya","Bashkortostan (Ufa)","Belgorodskaya","Bryanskaya","Buryatiya (Ulan-Ude)","Chechnya (Groznyy)","Chelyabinskaya","Chitinskaya","Chukotskiy (Anadyr')","Chuvashiya (Cheboksary)","Dagestan (Makhachkala)","Evenkiyskiy (Tura)","Ingushetiya (Nazran')","Irkutskaya","Ivanovskaya","Kabardino-Balkariya (Nal'chik)","Kaliningradskaya","Kalmykiya (Elista)","Kaluzhskaya","Kamchatskaya (Petropavlovsk-Kamchatskiy)","Karachayevo-Cherkesiya (Cherkessk)","Kareliya (Petrozavodsk)","Kemerovskaya","Khabarovskiy","Khakasiya (Abakan)","Khanty-Mansiyskiy (Khanty-Mansiysk)","Kirovskaya","Komi (Syktyvkar)","Komi-Permyatskiy (Kudymkar)","Koryakskiy (Palana)","Kostromskaya","Krasnodarskiy","Krasnoyarskiy","Kurganskaya","Kurskaya","Leningradskaya","Lipetskaya","Magadanskaya","Mariy-El (Yoshkar-Ola)","Mordoviya (Saransk)","Moskovskaya","Moskva (Moscow)","Murmanskaya","Nenetskiy (Nar'yan-Mar)","Nizhegorodskaya","Novgorodskaya","Novosibirskaya","Omskaya","Orenburgskaya","Orlovskaya (Orel)","Penzenskaya","Permskaya","Primorskiy (Vladivostok)","Pskovskaya","Rostovskaya","Ryazanskaya","Sakha (Yakutsk)","Sakhalinskaya (Yuzhno-Sakhalinsk)","Samarskaya","Sankt-Peterburg (Saint Petersburg)","Saratovskaya","Severnaya Osetiya-Alaniya [North Ossetia] (Vladikavkaz)","Smolenskaya","Stavropol'skiy","Sverdlovskaya (Yekaterinburg)","Tambovskaya","Tatarstan (Kazan')","Taymyrskiy (Dudinka)","Tomskaya","Tul'skaya","Tverskaya","Tyumenskaya","Tyva (Kyzyl)","Udmurtiya (Izhevsk)","Ul'yanovskaya","Ust'-Ordynskiy Buryatskiy (Ust'-Ordynskiy)","Vladimirskaya","Volgogradskaya","Vologodskaya","Voronezhskaya","Yamalo-Nenetskiy (Salekhard)","Yaroslavskaya","Yevreyskaya");
    private static final List<String> Rwanda=Arrays.asList("Choose States","Butare","Byumba","Cyangugu","Gikongoro","Gisenyi","Gitarama","Kibungo","Kibuye","Kigali Rurale","Kigali-ville","Ruhengeri","Umutara");
    private static final List<String> SaintHelena=Arrays.asList("Choose States","Ascension","Saint Helena","Tristan da Cunha");
    private static final List<String> SaintKittsAndNevis=Arrays.asList("Choose States","Christ Church Nichola Town","Saint Anne Sandy Point","Saint George Basseterre","Saint George Gingerland","Saint James Windward","Saint John Capisterre","Saint John Figtree","Saint Mary Cayon","Saint Paul Capisterre","Saint Paul Charlestown","Saint Peter Basseterre","Saint Thomas Lowland","Saint Thomas Middle Island","Trinity Palmetto Point");
    private static final List<String> SaintLucia=Arrays.asList("Choose States","Anse-la-Raye","Castries","Choiseul","Dauphin","Dennery","Gros Islet","Laborie","Micoud","Praslin","Soufriere","Vieux Fort");
    private static final List<String> SaintPierreAndMiquelon=Arrays.asList("Choose States","Miquelon","Saint Pierre");
    private static final List<String> SaintVincentAndTheGrenadines=Arrays.asList("Choose States","Charlotte","Grenadines","Saint Andrew","Saint David","Saint George","Saint Patrick");
    private static final List<String> Samoa=Arrays.asList("Choose States","A'ana","Aiga-i-le-Tai","Atua","Fa'asaleleaga","Gaga'emauga","Gagaifomauga","Palauli","Satupa'itea","Tuamasaga","Va'a-o-Fonoti","Vaisigano");
    private static final List<String> SanMarino=Arrays.asList("Choose States","Acquaviva","Borgo Maggiore","Chiesanuova","Domagnano","Faetano","Fiorentino","Monte Giardino","San Marino","Serravalle");
    private static final List<String> SaoTomeAndPrincipe=Arrays.asList("Choose States","Principe","Sao Tome");
    private static final List<String> SaudiArabia=Arrays.asList("Choose States","'Asir","Al Bahah","Al Hudud ash Shamaliyah","Al Jawf","Al Madinah","Al Qasim","Ar Riyad","Ash Sharqiyah (Eastern Province)","Ha'il","Jizan","Makkah","Najran","Tabuk");
    private static final List<String> Scotland=Arrays.asList("Choose States","Aberdeen City","Aberdeenshire","Angus","Argyll and Bute","City of Edinburgh","Clackmannanshire","Dumfries and Galloway","Dundee City","East Ayrshire","East Dunbartonshire","East Lothian","East Renfrewshire","Eilean Siar (Western Isles)","Falkirk","Fife","Glasgow City","Highland","Inverclyde","Midlothian","Moray","North Ayrshire","North Lanarkshire","Orkney Islands","Perth and Kinross","Renfrewshire","Shetland Islands","South Ayrshire","South Lanarkshire","Stirling","The Scottish Borders","West Dunbartonshire","West Lothian");
    private static final List<String> Senegal=Arrays.asList("Choose States","Dakar","Diourbel","Fatick","Kaolack","Kolda","Louga","Saint-Louis","Tambacounda","Thies","Ziguinchor");
    private static final List<String> Seychelles=Arrays.asList("Choose States","Anse aux Pins","Anse Boileau","Anse Etoile","Anse Louis","Anse Royale","Baie Lazare","Baie Sainte Anne","Beau Vallon","Bel Air","Bel Ombre","Cascade","Glacis","Grand' Anse (on Mahe)","Grand' Anse (on Praslin)","La Digue","La Riviere Anglaise","Mont Buxton","Mont Fleuri","Plaisance","Pointe La Rue","Port Glaud","Saint Louis","Takamaka");
    private static final List<String> SierraLeone=Arrays.asList("Choose States","Eastern","Northern","Southern","Western");
    private static final List<String> Singapore=Arrays.asList("Choose States","Singapore");
    private static final List<String> Slovakia=Arrays.asList("Choose States","Banskobystricky","Bratislavsky","Kosicky","Nitriansky","Presovsky","Trenciansky","Trnavsky","Zilinsky");
    private static final List<String> Slovenia=Arrays.asList("Choose States","Ajdovscina","Beltinci","Bled","Bohinj","Borovnica","Bovec","Brda","Brezice","Brezovica","Cankova-Tisina","Celje","Cerklje na Gorenjskem","Cerknica","Cerkno","Crensovci","Crna na Koroskem","Crnomelj","Destrnik-Trnovska Vas","Divaca","Dobrepolje","Dobrova-Horjul-Polhov Gradec","Dol pri Ljubljani","Domzale","Dornava","Dravograd","Duplek","Gorenja Vas-Poljane","Gorisnica","Gornja Radgona","Gornji Grad","Gornji Petrovci","Grosuplje","Hodos Salovci","Hrastnik","Hrpelje-Kozina","Idrija","Ig","Ilirska Bistrica","Ivancna Gorica","Izola","Jesenice","Jursinci","Kamnik","Kanal","Kidricevo","Kobarid","Kobilje","Kocevje","Komen","Koper","Kozje","Kranj","Kranjska Gora","Krsko","Kungota","Kuzma","Lasko","Lenart","Lendava","Litija","Ljubljana","Ljubno","Ljutomer","Logatec","Loska Dolina","Loski Potok","Luce","Lukovica","Majsperk","Maribor","Medvode","Menges","Metlika","Mezica","Miren-Kostanjevica","Mislinja","Moravce","Moravske Toplice","Mozirje","Murska Sobota","Muta","Naklo","Nazarje","Nova Gorica","Novo Mesto","Odranci","Ormoz","Osilnica","Pesnica","Piran","Pivka","Podcetrtek","Podvelka-Ribnica","Postojna","Preddvor","Ptuj","Puconci","Race-Fram","Radece","Radenci","Radlje ob Dravi","Radovljica","Ravne-Prevalje","Ribnica","Rogasevci","Rogaska Slatina","Rogatec","Ruse","Semic","Sencur","Sentilj","Sentjernej","Sentjur pri Celju","Sevnica","Sezana","Skocjan","Skofja Loka","Skofljica","Slovenj Gradec","Slovenska Bistrica","Slovenske Konjice","Smarje pri Jelsah","Smartno ob Paki","Sostanj","Starse","Store","Sveti Jurij","Tolmin","Trbovlje","Trebnje","Trzic","Turnisce","Velenje","Velike Lasce","Videm","Vipava","Vitanje","Vodice","Vojnik","Vrhnika","Vuzenica","Zagorje ob Savi","Zalec","Zavrc","Zelezniki","Ziri","Zrece");
    private static final List<String> SolomonIslands=Arrays.asList("Choose States","Bellona","Central","Choiseul (Lauru)","Guadalcanal","Honiara","Isabel","Makira","Malaita","Rennell","Temotu","Western");
    private static final List<String> Somalia=Arrays.asList("Choose States","Awdal","Bakool","Banaadir","Bari","Bay","Galguduud","Gedo","Hiiraan","Jubbada Dhexe","Jubbada Hoose","Mudug","Nugaal","Sanaag","Shabeellaha Dhexe","Shabeellaha Hoose","Sool","Togdheer","Woqooyi Galbeed");
    private static final List<String> SouthAfrica=Arrays.asList("Choose States","Eastern Cape","Free State","Gauteng","KwaZulu-Natal","Mpumalanga","North-West","Northern Cape","Northern Province","Western Cape");
    private static final List<String> SouthGeorgiaAndSouthSandwichIslands=Arrays.asList("Choose States","Bird Island","Bristol Island","Clerke Rocks","Montagu Island","Saunders Island","South Georgia","Southern Thule","Traversay Islands");
    private static final List<String> Spain=Arrays.asList("Choose States","Andalucia","Aragon","Asturias","Baleares (Balearic Islands)","Canarias (Canary Islands)","Cantabria","Castilla y Leon","Castilla-La Mancha","Cataluna","Ceuta","Communidad Valencian","Extremadura","Galicia","Islas Chafarinas","La Rioja","Madrid","Melilla","Murcia","Navarra","Pais Vasco (Basque Country)","Penon de Alhucemas","Penon de Velez de la Gomera");
    private static final List<String> SpratlyIslands=Arrays.asList("Choose States","Spratly Islands");
    private static final List<String> SriLanka=Arrays.asList("Choose States","Central","Eastern","North Central","North Eastern","North Western","Northern","Sabaragamuwa","Southern","Uva","Western");
    private static final List<String> Sudan=Arrays.asList("Choose States","A'ali an Nil","Al Bahr al Ahmar","Al Buhayrat","Al Jazirah","Al Khartum","Al Qadarif","Al Wahdah","An Nil al Abyad","An Nil al Azraq","Ash Shamaliyah","Bahr al Jabal","Gharb al Istiwa'iyah","Gharb Bahr al Ghazal","Gharb Darfur","Gharb Kurdufan","Janub Darfur","Janub Kurdufan","Junqali","Kassala","Nahr an Nil","Shamal Bahr al Ghazal","Shamal Darfur","Shamal Kurdufan","Sharq al Istiwa'iyah","Sinnar","Warab");
    private static final List<String> Suriname=Arrays.asList("Choose States","Brokopondo","Commewijne","Coronie","Marowijne","Nickerie","Para","Paramaribo","Saramacca","Sipaliwini","Wanica");
    private static final List<String> Svalbard=Arrays.asList("Choose States","Barentsoya","Bjornoya","Edgeoya","Hopen","Kvitoya","Nordaustandet","Prins Karls Forland","Spitsbergen");
    private static final List<String> Swaziland=Arrays.asList("Choose States","Hhohho","Lubombo","Manzini","Shiselweni");
    private static final List<String> Sweden=Arrays.asList("Choose States","Blekinge","Dalarnas","Gavleborgs","Gotlands","Hallands","Jamtlands","Jonkopings","Kalmar","Kronobergs","Norrbottens","Orebro","Ostergotlands","Skane","Sodermanlands","Stockholms","Uppsala","Varmlands","Vasterbottens","Vasternorrlands","Vastmanlands","Vastra Gotalands");
    private static final List<String> Switzerland=Arrays.asList("Choose States","Aargau","Ausser-Rhoden","Basel-Landschaft","Basel-Stadt","Bern","Fribourg","Geneve","Glarus","Graubunden","Inner-Rhoden","Jura","Luzern","Neuchatel","Nidwalden","Obwalden","Sankt Gallen","Schaffhausen","Schwyz","Solothurn","Thurgau","Ticino","Uri","Valais","Vaud","Zug","Zurich");
    private static final List<String> Syria=Arrays.asList("Choose States","Al Hasakah","Al Ladhiqiyah","Al Qunaytirah","Ar Raqqah","As Suwayda'","Dar'a","Dayr az Zawr","Dimashq","Halab","Hamah","Hims","Idlib","Rif Dimashq","Tartus");
    private static final List<String> Taiwan=Arrays.asList("Choose States","Chang-hua","Chi-lung","Chia-i","Chia-i","Chung-hsing-hsin-ts'un","Hsin-chu","Hsin-chu","Hua-lien","I-lan","Kao-hsiung","Kao-hsiung","Miao-li","Nan-t'ou","P'eng-hu","P'ing-tung","T'ai-chung","T'ai-chung","T'ai-nan","T'ai-nan","T'ai-pei","T'ai-pei","T'ai-tung","T'ao-yuan","Yun-lin");
    private static final List<String> Tajikistan=Arrays.asList("Choose States","Viloyati Khatlon","Viloyati Leninobod","Viloyati Mukhtori Kuhistoni Badakhshon");
    private static final List<String> Tanzania=Arrays.asList("Choose States","Arusha","Dar es Salaam","Dodoma","Iringa","Kagera","Kigoma","Kilimanjaro","Lindi","Mara","Mbeya","Morogoro","Mtwara","Mwanza","Pemba North","Pemba South","Pwani","Rukwa","Ruvuma","Shinyanga","Singida","Tabora","Tanga","Zanzibar Central/South","Zanzibar North","Zanzibar Urban/West");
    private static final List<String> Thailand=Arrays.asList("Choose States","Amnat Charoen","Ang Thong","Buriram","Chachoengsao","Chai Nat","Chaiyaphum","Chanthaburi","Chiang Mai","Chiang Rai","Chon Buri","Chumphon","Kalasin","Kamphaeng Phet","Kanchanaburi","Khon Kaen","Krabi","Krung Thep Mahanakhon (Bangkok)","Lampang","Lamphun","Loei","Lop Buri","Mae Hong Son","Maha Sarakham","Mukdahan","Nakhon Nayok","Nakhon Pathom","Nakhon Phanom","Nakhon Ratchasima","Nakhon Sawan","Nakhon Si Thammarat","Nan","Narathiwat","Nong Bua Lamphu","Nong Khai","Nonthaburi","Pathum Thani","Pattani","Phangnga","Phatthalung","Phayao","Phetchabun","Phetchaburi","Phichit","Phitsanulok","Phra Nakhon Si Ayutthaya","Phrae","Phuket","Prachin Buri","Prachuap Khiri Khan","Ranong","Ratchaburi","Rayong","Roi Et","Sa Kaeo","Sakon Nakhon","Samut Prakan","Samut Sakhon","Samut Songkhram","Sara Buri","Satun","Sing Buri","Sisaket","Songkhla","Sukhothai","Suphan Buri","Surat Thani","Surin","Tak","Trang","Trat","Ubon Ratchathani","Udon Thani","Uthai Thani","Uttaradit","Yala","Yasothon");
    private static final List<String> Tobago=Arrays.asList("Choose States","Tobago");
    private static final List<String> Toga=Arrays.asList("Choose States","De La Kara","Des Plateaux","Des Savanes","Du Centre","Maritime");
    private static final List<String> Tokelau=Arrays.asList("Choose States","Atafu","Fakaofo","Nukunonu");
    private static final List<String> Tonga=Arrays.asList("Choose States","Ha'apai","Tongatapu","Vava'u");
    private static final List<String> Trinidad=Arrays.asList("Choose States","Arima","Caroni","Mayaro","Nariva","Port-of-Spain","Saint Andrew","Saint David","Saint George","Saint Patrick","San Fernando","Victoria");
    private static final List<String> Tunisia=Arrays.asList("Choose States","Ariana","Beja","Ben Arous","Bizerte","El Kef","Gabes","Gafsa","Jendouba","Kairouan","Kasserine","Kebili","Mahdia","Medenine","Monastir","Nabeul","Sfax","Sidi Bou Zid","Siliana","Sousse","Tataouine","Tozeur","Tunis","Zaghouan");
    private static final List<String> Turkey=Arrays.asList("Choose States","Adana","Adiyaman","Afyon","Agri","Aksaray","Amasya","Ankara","Antalya","Ardahan","Artvin","Aydin","Balikesir","Bartin","Batman","Bayburt","Bilecik","Bingol","Bitlis","Bolu","Burdur","Bursa","Canakkale","Cankiri","Corum","Denizli","Diyarbakir","Duzce","Edirne","Elazig","Erzincan","Erzurum","Eskisehir","Gaziantep","Giresun","Gumushane","Hakkari","Hatay","Icel","Igdir","Isparta","Istanbul","Izmir","Kahramanmaras","Karabuk","Karaman","Kars","Kastamonu","Kayseri","Kilis","Kirikkale","Kirklareli","Kirsehir","Kocaeli","Konya","Kutahya","Malatya","Manisa","Mardin","Mugla","Mus","Nevsehir","Nigde","Ordu","Osmaniye","Rize","Sakarya","Samsun","Sanliurfa","Siirt","Sinop","Sirnak","Sivas","Tekirdag","Tokat","Trabzon","Tunceli","Usak","Van","Yalova","Yozgat","Zonguldak");
    private static final List<String> Turkmenistan=Arrays.asList("Choose States","Ahal Welayaty","Balkan Welayaty","Dashhowuz Welayaty","Lebap Welayaty","Mary Welayaty");
    private static final List<String> Tuvalu=Arrays.asList("Choose States","Tuvalu");
    private static final List<String> Uganda=Arrays.asList("Choose States","Adjumani","Apac","Arua","Bugiri","Bundibugyo","Bushenyi","Busia","Gulu","Hoima","Iganga","Jinja","Kabale","Kabarole","Kalangala","Kampala","Kamuli","Kapchorwa","Kasese","Katakwi","Kibale","Kiboga","Kisoro","Kitgum","Kotido","Kumi","Lira","Luwero","Masaka","Masindi","Mbale","Mbarara","Moroto","Moyo","Mpigi","Mubende","Mukono","Nakasongola","Nebbi","Ntungamo","Pallisa","Rakai","Rukungiri","Sembabule","Soroti","Tororo");
    private static final List<String> Ukraine=Arrays.asList("Choose States","Avtonomna Respublika Krym (Simferopol')","Cherkas'ka (Cherkasy)","Chernihivs'ka (Chernihiv)","Chernivets'ka (Chernivtsi)","Dnipropetrovs'ka (Dnipropetrovs'k)","Donets'ka (Donets'k)","Ivano-Frankivs'ka (Ivano-Frankivs'k)","Kharkivs'ka (Kharkiv)","Khersons'ka (Kherson)","Khmel'nyts'ka (Khmel'nyts'kyy)","Kirovohrads'ka (Kirovohrad)","Kyyiv","Kyyivs'ka (Kiev)","L'vivs'ka (L'viv)","Luhans'ka (Luhans'k)","Mykolayivs'ka (Mykolayiv)","Odes'ka (Odesa)","Poltavs'ka (Poltava)","Rivnens'ka (Rivne)","Sevastopol'","Sums'ka (Sumy)","Ternopil's'ka (Ternopil')","Vinnyts'ka (Vinnytsya)","Volyns'ka (Luts'k)","Zakarpats'ka (Uzhhorod)","Zaporiz'ka (Zaporizhzhya)","Zhytomyrs'ka (Zhytomyr)");
    private static final List<String> UnitedArabEmirates=Arrays.asList("Choose States","'Ajman","Abu Zaby (Abu Dhabi)","Al Fujayrah","Ash Shariqah (Sharjah)","Dubayy (Dubai)","Ra's al Khaymah","Umm al Qaywayn");
    private static final List<String> UnitedKingdom=Arrays.asList("Choose States","Barking and Dagenham","Barnet","Barnsley","Bath and North East Somerset","Bedfordshire","Bexley","Birmingham","Blackburn with Darwen","Blackpool","Bolton","Bournemouth","Bracknell Forest","Bradford","Brent","Brighton and Hove","Bromley","Buckinghamshire","Bury","Calderdale","Cambridgeshire","Camden","Cheshire","City of Bristol","City of Kingston upon Hull","City of London","Cornwall","Coventry","Croydon","Cumbria","Darlington","Derby","Derbyshire","Devon","Doncaster","Dorset","Dudley","Durham","Ealing","East Riding of Yorkshire","East Sussex","Enfield","Essex","Gateshead","Gloucestershire","Greenwich","Hackney","Halton","Hammersmith and Fulham","Hampshire","Haringey","Harrow","Hartlepool","Havering","Herefordshire","Hertfordshire","Hillingdon","Hounslow","Isle of Wight","Islington","Kensington and Chelsea","Kent","Kingston upon Thames","Kirklees","Knowsley","Lambeth","Lancashire","Leeds","Leicester","Leicestershire","Lewisham","Lincolnshire","Liverpool","Luton","Manchester","Medway","Merton","Middlesbrough","Milton Keynes","Newcastle upon Tyne","Newham","Norfolk","North East Lincolnshire","North Lincolnshire","North Somerset","North Tyneside","North Yorkshire","Northamptonshire","Northumberland","Nottingham","Nottinghamshire","Oldham","Oxfordshire","Peterborough","Plymouth","Poole","Portsmouth","Reading","Redbridge","Redcar and Cleveland","Richmond upon Thames","Rochdale","Rotherham","Rutland","Salford","Sandwell","Sefton","Sheffield","Shropshire","Slough","Solihull","Somerset","South Gloucestershire","South Tyneside","Southampton","Southend-on-Sea","Southwark","St. Helens","Staffordshire","Stockport","Stockton-on-Tees","Stoke-on-Trent","Suffolk","Sunderland","Surrey","Sutton","Swindon","Tameside","Telford and Wrekin","Thurrock","Torbay","Tower Hamlets","Trafford","Wakefield","Walsall","Waltham Forest","Wandsworth","Warrington","Warwickshire","West Berkshire","West Sussex","Westminster","Wigan","Wiltshire","Windsor and Maidenhead","Wirral","Wokingham","Wolverhampton","Worcestershire","York");
    private static final List<String> Uruguay=Arrays.asList("Choose States","Artigas","Canelones","Cerro Largo","Colonia","Durazno","Flores","Florida","Lavalleja","Maldonado","Montevideo","Paysandu","Rio Negro","Rivera","Rocha","Salto","San Jose","Soriano","Tacuarembo","Treinta y Tres");
    private static final List<String> USA=Arrays.asList("Choose States","Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","District of Columbia","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Carolina","North Dakota","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming");
    private static final List<String> Uzbekistan=Arrays.asList("Choose States","Andijon Wiloyati","Bukhoro Wiloyati","Farghona Wiloyati","Jizzakh Wiloyati","Khorazm Wiloyati (Urganch)","Namangan Wiloyati","Nawoiy Wiloyati","Qashqadaryo Wiloyati (Qarshi)","Qoraqalpoghiston (Nukus)","Samarqand Wiloyati","Sirdaryo Wiloyati (Guliston)","Surkhondaryo Wiloyati (Termiz)","Toshkent Shahri","Toshkent Wiloyati");
    private static final List<String> Vanuatu=Arrays.asList("Choose States","Malampa","Penama","Sanma","Shefa","Tafea","Torba");
    private static final List<String> Venezuela=Arrays.asList("Choose States","Amazonas","Anzoategui","Apure","Aragua","Barinas","Bolivar","Carabobo","Cojedes","Delta Amacuro","Dependencias Federales","Distrito Federal","Falcon","Guarico","Lara","Merida","Miranda","Monagas","Nueva Esparta","Portuguesa","Sucre","Tachira","Trujillo","Vargas","Yaracuy","Zulia");
    private static final List<String> Vietnam=Arrays.asList("Choose States","An Giang","Ba Ria-Vung Tau","Bac Giang","Bac Kan","Bac Lieu","Bac Ninh","Ben Tre","Binh Dinh","Binh Duong","Binh Phuoc","Binh Thuan","Ca Mau","Can Tho","Cao Bang","Da Nang","Dac Lak","Dong Nai","Dong Thap","Gia Lai","Ha Giang","Ha Nam","Ha Noi","Ha Tay","Ha Tinh","Hai Duong","Hai Phong","Ho Chi Minh","Hoa Binh","Hung Yen","Khanh Hoa","Kien Giang","Kon Tum","Lai Chau","Lam Dong","Lang Son","Lao Cai","Long An","Nam Dinh","Nghe An","Ninh Binh","Ninh Thuan","Phu Tho","Phu Yen","Quang Binh","Quang Nam","Quang Ngai","Quang Ninh","Quang Tri","Soc Trang","Son La","Tay Ninh","Thai Binh","Thai Nguyen","Thanh Hoa","Thua Thien-Hue","Tien Giang","Tra Vinh","Tuyen Quang","Vinh Long","Vinh Phuc","Yen Bai");
    private static final List<String> VirginIslands=Arrays.asList("Choose States","Saint Croix","Saint John","Saint Thomas");
    private static final List<String> Wales=Arrays.asList("Choose States","Blaenau Gwent","Bridgend","Caerphilly","Cardiff","Carmarthenshire","Ceredigion","Conwy","Denbighshire","Flintshire","Gwynedd","Isle of Anglesey","Merthyr Tydfil","Monmouthshire","Neath Port Talbot","Newport","Pembrokeshire","Powys","Rhondda Cynon Taff","Swansea","The Vale of Glamorgan","Torfaen","Wrexham");
    private static final List<String> WallisAndFutuna=Arrays.asList("Choose States","Alo","Sigave","Wallis");
    private static final List<String> WestBank=Arrays.asList("Choose States","West Bank");
    private static final List<String> WesternSahara=Arrays.asList("Choose States","Western Sahara");
    private static final List<String> Yemen=Arrays.asList("Choose States","'Adan","'Ataq","Abyan","Al Bayda'","Al Hudaydah","Al Jawf","Al Mahrah","Al Mahwit","Dhamar","Hadhramawt","Hajjah","Ibb","Lahij","Ma'rib","Sa'dah","San'a'","Ta'izz");
    private static final List<String> Yugoslavia=Arrays.asList("Choose States","Kosovo","Montenegro","Serbia","Vojvodina");
    private static final List<String> Zambia=Arrays.asList("Choose States","Central","Copperbelt","Eastern","Luapula","Lusaka","North-Western","Northern","Southern","Western");
    private static final List<String> Zimbabwe=Arrays.asList("Choose States","Bulawayo","Harare","ManicalandMashonaland Central","Mashonaland East","Mashonaland West","Masvingo","Matabeleland North","Matabeleland South","Midlands");



    public static Map<String, List<String>> map = new HashMap<String, List<String>>();
    StateMap(){
        initMap();
    }

  /*  private List<String> getState(Country)
    {
        List<String> states=map.get(Country);
        return states;
    }*/

    private void initMap() {
        map.put("Choose Country", chooseCountry);
        map.put("Afghanistan", Afghanistan);
        map.put("Albania", Albania);
        map.put("Algeria", Algeria);
        map.put("American samoa", AmericanSamoa);
        map.put("Angola", Angola);
        map.put("Anguilla", Anguilla);
        map.put("Antartica", Antartica);
        map.put("Antigua and barbuda", AntiguaAndBarbuda);
        map.put("Argentina", Argentina);
        map.put("Armenia", Armenia);
        map.put("Aruba", Aruba);
        map.put("Ashmore and cartier island", AshmoreAndCartierIsland);
        map.put("Australia", Australia);
        map.put("Austria", Austria);
        map.put("Azerbaijan", Azerbaijan);
        map.put("Bahamas", Bahamas);
        map.put("Bahrain", Bahrain);
        map.put("Bangladesh", Bangladesh);
        map.put("Barbados", Barbados);
        map.put("Belarus", Belarus);
        map.put("Belgium", Belgium);
        map.put("Belize", Belize);
        map.put("Benin", Benin);
        map.put("Bermuda", Bermuda);
        map.put("Bhutan", Bhutan);
        map.put("Bolivia", Bolivia);
        map.put("Bosnia and herzegovina", BosniaAndHerzegovina);
        map.put("Botswana", Botswana);
        map.put("Brazil", Brazil);
        map.put("British virgin islands", BritishVirginIslands);
        map.put("Brunei", Brunei);
        map.put("Bulgaria", Bulgaria);
        map.put("Burkina faso", BurkinaFaso);
        map.put("Burma", Burma);
        map.put("Burundi", Burundi);
        map.put("Cambodia", Cambodia);
        map.put("Cameroon", Cameroon);
        map.put("Canada", Canada);
        map.put("Cape verde", CapeVerde);
        map.put("Cayman islands", CaymanIslands);
        map.put("Central african republic", CentralAfricanRepublic);
        map.put("Chad", Chad);
        map.put("Chile", Chile);
        map.put("China", China);
        map.put("Christmas island", ChristmasIsland);
        map.put("Clipperton island", ClippertonIsland);
        map.put("Cocos islands", CocosIslands);
        map.put("Colombia", Colombia);
        map.put("Comoros", Comoros);
        map.put("Congo democratic republic of the", CongoDemocraticRepublicOfThe);
        map.put("Congo republic of the", CongoRepublicOfThe);
        map.put("Cook islands", CookIslands);
        map.put("Costa rica", CostaRica);
        map.put("Cote d'ivoire ", CoteDIvoire);
        map.put("Croatia", Croatia);
        map.put("Cuba", Cuba);
        map.put("Cyprus", Cyprus);
        map.put("Czeck republic", CzeckRepublic);
        map.put("Denmark", Denmark);
        map.put("Djibouti", Djibouti);
        map.put("Dominica", Dominica);
        map.put("Dominican republic", DominicanRepublic);
        map.put("Ecuador", Ecuador);
        map.put("Egypt", Egypt);
        map.put("El salvador", ElSalvador);
        map.put("Equatorial guinea", EquatorialGuinea);
        map.put("Eritrea", Eritrea);
        map.put("Estonia", Estonia);
        map.put("Ethiopia", Ethiopia);
        map.put("Europa island", EuropaIsland);
        map.put("Falkland islands", FalklandIslands);
        map.put("Faroe islands", FaroeIslands);
        map.put("Fiji", Fiji);
        map.put("Finland", Finland);
        map.put("France", France);
        map.put("French guiana", FrenchGuiana);
        map.put("French polynesia", FrenchPolynesia);
        map.put("French southern and antarctic lands", FrenchSouthernAndAntarcticLands);
        map.put("Gabon", Gabon);
        map.put("Gambia the", GambiaThe);
        map.put("Gaza strip", GazaStrip);
        map.put("Georgia", Georgia);
        map.put("Germany", Germany);
        map.put("Ghana", Ghana);
        map.put("Gibraltar", Gibraltar);
        map.put("Glorioso islands", GloriosoIslands);
        map.put("Greece", Greece);
        map.put("Greenland", Greenland);
        map.put("Grenada", Grenada);
        map.put("Guadeloupe", Guadeloupe);
        map.put("Guam", Guam);
        map.put("Guatemala", Guatemala);
        map.put("Guernsey", Guernsey);
        map.put("Guinea", Guinea);
        map.put("GuineaBissau", GuineaBissau);
        map.put("Guyana", Guyana);
        map.put("Haiti", Haiti);
        map.put("Heard island and mcDonald islands", HeardIslandAndMcDonaldIslands);
        map.put("HolySee", HolySee);
        map.put("Honduras", Honduras);
        map.put("Hong Kong", HongKong);
        map.put("Howland island", HowlandIsland);
        map.put("Hungary", Hungary);
        map.put("Iceland", Iceland);
        map.put("India", India);
        map.put("Indonesia", Indonesia);
        map.put("Iran", Iran);
        map.put("Iraq", Iraq);
        map.put("Ireland", Ireland);
        map.put("Ireland northern", IrelandNorthern);
        map.put("Israel", Israel);
        map.put("Italy", Italy);
        map.put("Jamaica", Jamaica);
        map.put("Jan mayen", JanMayen);
        map.put("Japan", Japan);
        map.put("Jarvis island", JarvisIsland);
        map.put("Jersey", Jersey);
        map.put("Johnston atoll", JohnstonAtoll);
        map.put("Jordan", Jordan);
        map.put("Juan de nova island", JuanDeNovaIsland);
        map.put("Kazakhstan", Kazakhstan);
        map.put("Kenya", Kenya);
        map.put("Kiribati", Kiribati);
        map.put("Korea North", KoreaNorth);
        map.put("Korea South", KoreaSouth);
        map.put("Kuwait", Kuwait);
        map.put("Kyrgyzstan", Kyrgyzstan);
        map.put("Laos", Laos);
        map.put("Latvia", Latvia);
        map.put("Lebanon", Lebanon);
        map.put("Lesotho", Lesotho);
        map.put("Liberia", Liberia);
        map.put("Libya", Libya);
        map.put("Liechtenstein", Liechtenstein);
        map.put("Lithuania", Lithuania);
        map.put("Luxembourg", Luxembourg);
        map.put("Macau", Macau);
        map.put("Macedonia", MacedoniaFormerYugoslavRepublicOf);
        map.put("Madagascar", Madagascar);
        map.put("Malawi", Malawi);
        map.put("Malaysia", Malaysia);
        map.put("Maldives", Maldives);
        map.put("Mali", Mali);
        map.put("Malta", Malta);
        map.put("Man isle of", ManIsleOf);
        map.put("Marshall islands", MarshallIslands);
        map.put("Martinique", Martinique);
        map.put("Mauritania", Mauritania);
        map.put("Mauritius", Mauritius);
        map.put("Mayotte", Mayotte);
        map.put("Mexico", Mexico);
        map.put("Micronesia", MicronesiaFederatedStatesOf);
        map.put("Midway islands", MidwayIslands);
        map.put("Moldova", Moldova);
        map.put("Monaco", Monaco);
        map.put("Mongolia", Mongolia);
        map.put("Montserrat", Montserrat);
        map.put("Morocco", Morocco);
        map.put("Mozambique", Mozambique);
        map.put("Namibia", Namibia);
        map.put("Nauru", Nauru);
        map.put("Nepal", Nepal);
        map.put("Netherlands", Netherlands);
        map.put("Netherlands antilles", NetherlandsAntilles);
        map.put("New caledonia", NewCaledonia);
        map.put("New Zealand", NewZealand);
        map.put("Nicaragua", Nicaragua);
        map.put("Niger", Niger);
        map.put("Nigeria", Nigeria);
        map.put("Niue", Niue);
        map.put("Norfolk island", NorfolkIsland);
        map.put("Northern mariana islands", NorthernMarianaIslands);
        map.put("Norway", Norway);
        map.put("Oman", Oman);
        map.put("Pakistan", Pakistan);
        map.put("Palau", Palau);
        map.put("Panama", Panama);
        map.put("Papua new guinea", PapuaNewGuinea);
        map.put("Paraguay", Paraguay);
        map.put("Peru", Peru);
        map.put("Philippines", Philippines);
        map.put("Poland", Poland);
        map.put("Portugal", Portugal);
        map.put("Puerto rico", PuertoRico);
        map.put("Qatar", Qatar);
        map.put("Reunion", Reunion);
        map.put("Romainia", Romainia);
        map.put("Russia", Russia);
        map.put("Rwanda", Rwanda);
        map.put("Saint helena", SaintHelena);
        map.put("Saint kitts and nevis", SaintKittsAndNevis);
        map.put("Saint lucia", SaintLucia);
        map.put("Saint pierre and miquelon", SaintPierreAndMiquelon);
        map.put("Saint vincent and the grenadines", SaintVincentAndTheGrenadines);
        map.put("Samoa", Samoa);
        map.put("San marino", SanMarino);
        map.put("Sao tome and principe", SaoTomeAndPrincipe);
        map.put("Saudi arabia", SaudiArabia);
        map.put("Scotland", Scotland);
        map.put("Senegal", Senegal);
        map.put("Seychelles", Seychelles);
        map.put("Sierra leone", SierraLeone);
        map.put("Singapore", Singapore);
        map.put("Slovakia", Slovakia);
        map.put("Slovenia", Slovenia);
        map.put("Solomon islands", SolomonIslands);
        map.put("Somalia", Somalia);
        map.put("South africa", SouthAfrica);
        map.put("South georgia and south sandwich islands", SouthGeorgiaAndSouthSandwichIslands);
        map.put("Spain", Spain);
        map.put("Spratly islands", SpratlyIslands);
        map.put("Sri lanka", SriLanka);
        map.put("Sudan", Sudan);
        map.put("Suriname", Suriname);
        map.put("Svalbard", Svalbard);
        map.put("Swaziland", Swaziland);
        map.put("Sweden", Sweden);
        map.put("Switzerland", Switzerland);
        map.put("Syria", Syria);
        map.put("Taiwan", Taiwan);
        map.put("Tajikistan", Tajikistan);
        map.put("Tanzania", Tanzania);
        map.put("Thailand", Thailand);
        map.put("Tobago", Tobago);
        map.put("Toga", Toga);
        map.put("Tokelau", Tokelau);
        map.put("Tonga", Tonga);
        map.put("Trinidad", Trinidad);
        map.put("Tunisia", Tunisia);
        map.put("Turkey", Turkey);
        map.put("Turkmenistan", Turkmenistan);
        map.put("Tuvalu", Tuvalu);
        map.put("Uganda", Uganda);
        map.put("Ukraine", Ukraine);
        map.put("United Arab Emirates", UnitedArabEmirates);
        map.put("United Kingdom", UnitedKingdom);
        map.put("Uruguay", Uruguay);
        map.put("USA", USA);
        map.put("Uzbekistan", Uzbekistan);
        map.put("Vanuatu", Vanuatu);
        map.put("Venezuela", Venezuela);
        map.put("Vietnam", Vietnam);
        map.put("Virgin islands", VirginIslands);
        map.put("Wales", Wales);
        map.put("Wallis and futuna", WallisAndFutuna);
        map.put("West bank", WestBank);
        map.put("Western sahara", WesternSahara);
        map.put("Yemen", Yemen);
        map.put("Yugoslavia", Yugoslavia);
        map.put("Zambia", Zambia);
        map.put("Zimbabwe", Zimbabwe);


    }
}
